import { PromiseTypes } from '../../../core/promise';
import { IApiService } from '../../../http/api-service';
import { EntityServiceTypes as SvcDef } from '../../interfaces/Ams/EntityService';
import AbortablePromise = PromiseTypes.AbortablePromise;
import Requests = SvcDef.Requests;
import Responses = SvcDef.Responses;
import IEntityService = SvcDef.IEntityService;
export * from '../../../http/api-service';
export * from '../../interfaces/Ams/EntityService';
export declare class EntityService implements IEntityService {
    private _service;
    constructor(service: IApiService);
    AddAlias(request: Requests.AddAlias): AbortablePromise<Responses.AddAlias>;
    AddGroupAlias(request: Requests.AddGroupAlias): AbortablePromise<Responses.AddGroupAlias>;
    AddIdentifier(request: Requests.AddIdentifier): AbortablePromise<Responses.AddIdentifier>;
    AddIdentifiers(request: Requests.AddIdentifiers): AbortablePromise<Responses.AddIdentifiers>;
    AddSplit(request: Requests.AddSplit): AbortablePromise<Responses.AddSplit>;
    AliasAssets(request: Requests.AliasAssets): AbortablePromise<Responses.AliasAssets>;
    Aliases(request: Requests.Aliases): AbortablePromise<Responses.Aliases>;
    AllAliases(request: Requests.AllAliases): AbortablePromise<Responses.AllAliases>;
    AllGroupAliases(request: Requests.AllGroupAliases): AbortablePromise<Responses.AllGroupAliases>;
    AssetCostHistory(request: Requests.AssetCostHistory): AbortablePromise<Responses.AssetCostHistory>;
    Attributes(request: Requests.Attributes): AbortablePromise<Responses.Attributes>;
    ChildPaths(request: Requests.ChildPaths): AbortablePromise<Responses.ChildPaths>;
    Children(request: Requests.Children): AbortablePromise<Responses.Children>;
    CloneWorkOrderEntities(request: Requests.CloneWorkOrderEntities): AbortablePromise<Responses.CloneWorkOrderEntities>;
    Configuration(request: Requests.Configuration): AbortablePromise<Responses.Configuration>;
    CostHistory(request: Requests.CostHistory): AbortablePromise<Responses.CostHistory>;
    CostTotal(request: Requests.CostTotal): AbortablePromise<Responses.CostTotal>;
    DirectParent(request: Requests.DirectParent): AbortablePromise<Responses.DirectParent>;
    DistinctValues(request: Requests.DistinctValues): AbortablePromise<Responses.DistinctValues>;
    DomainTypes(request: Requests.DomainTypes): AbortablePromise<Responses.DomainTypes>;
    EntityUidField(request: Requests.EntityUidField): AbortablePromise<Responses.EntityUidField>;
    EntityUrlInfos(request: Requests.EntityUrlInfos): AbortablePromise<Responses.EntityUrlInfos>;
    FilterRecordToWorkOrderEntity(request: Requests.FilterRecordToWorkOrderEntity): AbortablePromise<Responses.FilterRecordToWorkOrderEntity>;
    FiveNumberSummary(request: Requests.FiveNumberSummary): AbortablePromise<Responses.FiveNumberSummary>;
    GetByIdentifier(request: Requests.GetByIdentifier): AbortablePromise<Responses.GetByIdentifier>;
    GetByIdentifiers(request: Requests.GetByIdentifiers): AbortablePromise<Responses.GetByIdentifiers>;
    GISAttributes(request: Requests.GISAttributes): AbortablePromise<Responses.GISAttributes>;
    GroupAliases(request: Requests.GroupAliases): AbortablePromise<Responses.GroupAliases>;
    GroupByType(request: Requests.GroupByType): AbortablePromise<Responses.GroupByType>;
    Groups(request: Requests.Groups): AbortablePromise<Responses.Groups>;
    InspectionCostHistory(request: Requests.InspectionCostHistory): AbortablePromise<Responses.InspectionCostHistory>;
    Orphans(request: Requests.Orphans): AbortablePromise<Responses.Orphans>;
    ParentPaths(request: Requests.ParentPaths): AbortablePromise<Responses.ParentPaths>;
    Parents(request: Requests.Parents): AbortablePromise<Responses.Parents>;
    ProcessSplits(request: Requests.ProcessSplits): AbortablePromise<Responses.ProcessSplits>;
    PwEntities(request: Requests.PwEntities): AbortablePromise<Responses.PwEntities>;
    RemoveAlias(request: Requests.RemoveAlias): AbortablePromise<Responses.RemoveAlias>;
    RemoveGroupAlias(request: Requests.RemoveGroupAlias): AbortablePromise<Responses.RemoveGroupAlias>;
    Resolve(request: Requests.Resolve): AbortablePromise<Responses.Resolve>;
    Search(request: Requests.Search): AbortablePromise<Responses.Search>;
    SearchAsWorkOrderEntity(request: Requests.SearchAsWorkOrderEntity): AbortablePromise<Responses.SearchAsWorkOrderEntity>;
    SplitEntities(request: Requests.SplitEntities): AbortablePromise<Responses.SplitEntities>;
    Splits(request: Requests.Splits): AbortablePromise<Responses.Splits>;
    SubTypes(request: Requests.SubTypes): AbortablePromise<Responses.SubTypes>;
    TypeRelationships(request: Requests.TypeRelationships): AbortablePromise<Responses.TypeRelationships>;
    Types(request: Requests.Types): AbortablePromise<Responses.Types>;
    VisibleFields(request: Requests.VisibleFields): AbortablePromise<Responses.VisibleFields>;
    WorkActivityHistory(request: Requests.WorkActivityHistory): AbortablePromise<Responses.WorkActivityHistory>;
    ErrorCodes: {
        UnknownError: number;
        ErrorUnknownEntityType: number;
        ErrorNoWorkHistory: number;
        ErrorUnknownDestinationEntity: number;
        ErrorIdentifierAlreadyInUse: number;
        InvalidField: number;
    };
    WarningCodes: {
        WarningItemNotFound: number;
        WarningEmptyOrNullField: number;
        WarningNoUidSetForEntityType: number;
        WarningNoValidRelationships: number;
    };
}
