import { PromiseTypes } from '../../../core/promise';
import { IApiService } from '../../../http/api-service';
import { AttachmentsServiceTypes as SvcDef } from '../../interfaces/Ams/AttachmentsService';
import AbortablePromise = PromiseTypes.AbortablePromise;
import Requests = SvcDef.Requests;
import Responses = SvcDef.Responses;
import IAttachmentsService = SvcDef.IAttachmentsService;
export * from '../../../http/api-service';
export * from '../../interfaces/Ams/AttachmentsService';
export declare class AttachmentsService implements IAttachmentsService {
    private _service;
    constructor(service: IApiService);
    AddActivityFileLink(request: Requests.AddActivityFileLink): AbortablePromise<Responses.AddActivityFileLink>;
    AddInspectionAttachment(request: Requests.AddInspectionAttachment): AbortablePromise<Responses.AddInspectionAttachment>;
    AddRequestAttachment(request: Requests.AddRequestAttachment): AbortablePromise<Responses.AddRequestAttachment>;
    AddTvInspectionAttachment(request: Requests.AddTvInspectionAttachment): AbortablePromise<Responses.AddTvInspectionAttachment>;
    AddTvObservationAttachment(request: Requests.AddTvObservationAttachment): AbortablePromise<Responses.AddTvObservationAttachment>;
    AddWorkOrderAttachment(request: Requests.AddWorkOrderAttachment): AbortablePromise<Responses.AddWorkOrderAttachment>;
    DeleteInspectionAttachments(request: Requests.DeleteInspectionAttachments): AbortablePromise<Responses.DeleteInspectionAttachments>;
    DeleteRequestAttachments(request: Requests.DeleteRequestAttachments): AbortablePromise<Responses.DeleteRequestAttachments>;
    DeleteRequisitionAttachments(request: Requests.DeleteRequisitionAttachments): AbortablePromise<Responses.DeleteRequisitionAttachments>;
    DeleteTvInspectionAttachments(request: Requests.DeleteTvInspectionAttachments): AbortablePromise<Responses.DeleteTvInspectionAttachments>;
    DeleteTvObservationAttachments(request: Requests.DeleteTvObservationAttachments): AbortablePromise<Responses.DeleteTvObservationAttachments>;
    DeleteWorkOrderAttachments(request: Requests.DeleteWorkOrderAttachments): AbortablePromise<Responses.DeleteWorkOrderAttachments>;
    DownloadInspectionAttachment(request: Requests.DownloadInspectionAttachment): AbortablePromise<Responses.DownloadInspectionAttachment>;
    DownloadRequestAttachment(request: Requests.DownloadRequestAttachment): AbortablePromise<Responses.DownloadRequestAttachment>;
    DownloadTvInspectionAttachment(request: Requests.DownloadTvInspectionAttachment): AbortablePromise<Responses.DownloadTvInspectionAttachment>;
    DownloadTvObservationAttachment(request: Requests.DownloadTvObservationAttachment): AbortablePromise<Responses.DownloadTvObservationAttachment>;
    DownloadWorkOrderAttachment(request: Requests.DownloadWorkOrderAttachment): AbortablePromise<Responses.DownloadWorkOrderAttachment>;
    InspectionAttachmentById(request: Requests.InspectionAttachmentById): AbortablePromise<Responses.InspectionAttachmentById>;
    InspectionAttachments(request: Requests.InspectionAttachments): AbortablePromise<Responses.InspectionAttachments>;
    RequestAttachmentById(request: Requests.RequestAttachmentById): AbortablePromise<Responses.RequestAttachmentById>;
    RequestAttachments(request: Requests.RequestAttachments): AbortablePromise<Responses.RequestAttachments>;
    TvInspectionAttachmentById(request: Requests.TvInspectionAttachmentById): AbortablePromise<Responses.TvInspectionAttachmentById>;
    TvInspectionAttachments(request: Requests.TvInspectionAttachments): AbortablePromise<Responses.TvInspectionAttachments>;
    TvObservationAttachmentById(request: Requests.TvObservationAttachmentById): AbortablePromise<Responses.TvObservationAttachmentById>;
    TvObservationAttachments(request: Requests.TvObservationAttachments): AbortablePromise<Responses.TvObservationAttachments>;
    WorkOrderAttachments(request: Requests.WorkOrderAttachments): AbortablePromise<Responses.WorkOrderAttachments>;
    ErrorCodes: {};
    WarningCodes: {};
}
