define(["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    var Enums;
    (function (Enums) {
        var AbcCatClass;
        (function (AbcCatClass) {
            AbcCatClass[AbcCatClass["A"] = 1] = "A";
            AbcCatClass[AbcCatClass["B"] = 2] = "B";
            AbcCatClass[AbcCatClass["C"] = 3] = "C";
            AbcCatClass[AbcCatClass["NA"] = 4] = "NA";
        })(AbcCatClass = Enums.AbcCatClass || (Enums.AbcCatClass = {}));
        var ActionType;
        (function (ActionType) {
            ActionType[ActionType["Unknown"] = 0] = "Unknown";
            ActionType[ActionType["ActivityUpdate"] = 1] = "ActivityUpdate";
            ActionType[ActionType["Email"] = 2] = "Email";
            ActionType[ActionType["WebHook"] = 3] = "WebHook";
        })(ActionType = Enums.ActionType || (Enums.ActionType = {}));
        var ActivityLinkActivityType;
        (function (ActivityLinkActivityType) {
            ActivityLinkActivityType[ActivityLinkActivityType["Null"] = 0] = "Null";
            ActivityLinkActivityType[ActivityLinkActivityType["Case"] = 1] = "Case";
            ActivityLinkActivityType[ActivityLinkActivityType["Inspection"] = 2] = "Inspection";
            ActivityLinkActivityType[ActivityLinkActivityType["ServiceRequest"] = 3] = "ServiceRequest";
            ActivityLinkActivityType[ActivityLinkActivityType["WorkOrder"] = 4] = "WorkOrder";
            ActivityLinkActivityType[ActivityLinkActivityType["WIPCase"] = 5] = "WIPCase";
        })(ActivityLinkActivityType = Enums.ActivityLinkActivityType || (Enums.ActivityLinkActivityType = {}));
        var ActivityLinkType;
        (function (ActivityLinkType) {
            ActivityLinkType[ActivityLinkType["Null"] = 0] = "Null";
            ActivityLinkType[ActivityLinkType["Parent"] = 1] = "Parent";
            ActivityLinkType[ActivityLinkType["Related"] = 2] = "Related";
        })(ActivityLinkType = Enums.ActivityLinkType || (Enums.ActivityLinkType = {}));
        var ApiVersionEnum;
        (function (ApiVersionEnum) {
            ApiVersionEnum[ApiVersionEnum["V20121"] = 0] = "V20121";
            ApiVersionEnum[ApiVersionEnum["V2013"] = 1] = "V2013";
            ApiVersionEnum[ApiVersionEnum["V2014"] = 2] = "V2014";
            ApiVersionEnum[ApiVersionEnum["V2015"] = 3] = "V2015";
            ApiVersionEnum[ApiVersionEnum["V15_1"] = 4] = "V15_1";
            ApiVersionEnum[ApiVersionEnum["V15_1_1"] = 5] = "V15_1_1";
            ApiVersionEnum[ApiVersionEnum["V15_1_2"] = 6] = "V15_1_2";
            ApiVersionEnum[ApiVersionEnum["V15_1_3"] = 7] = "V15_1_3";
            ApiVersionEnum[ApiVersionEnum["V15_1_4"] = 8] = "V15_1_4";
            ApiVersionEnum[ApiVersionEnum["V15_1_5"] = 9] = "V15_1_5";
            ApiVersionEnum[ApiVersionEnum["V15_1_6"] = 10] = "V15_1_6";
            ApiVersionEnum[ApiVersionEnum["V15_2"] = 11] = "V15_2";
            ApiVersionEnum[ApiVersionEnum["V15_2_1"] = 12] = "V15_2_1";
            ApiVersionEnum[ApiVersionEnum["V15_2_2"] = 13] = "V15_2_2";
            ApiVersionEnum[ApiVersionEnum["V15_2_3"] = 14] = "V15_2_3";
            ApiVersionEnum[ApiVersionEnum["V15_2_4"] = 15] = "V15_2_4";
            ApiVersionEnum[ApiVersionEnum["V15_2_5"] = 16] = "V15_2_5";
            ApiVersionEnum[ApiVersionEnum["V15_2_6"] = 17] = "V15_2_6";
            ApiVersionEnum[ApiVersionEnum["V15_2_7"] = 18] = "V15_2_7";
            ApiVersionEnum[ApiVersionEnum["V15_3"] = 19] = "V15_3";
            ApiVersionEnum[ApiVersionEnum["V15_3_1"] = 20] = "V15_3_1";
            ApiVersionEnum[ApiVersionEnum["V15_3_2"] = 21] = "V15_3_2";
            ApiVersionEnum[ApiVersionEnum["V15_3_3"] = 22] = "V15_3_3";
            ApiVersionEnum[ApiVersionEnum["V15_3_4"] = 23] = "V15_3_4";
            ApiVersionEnum[ApiVersionEnum["V15_3_5"] = 24] = "V15_3_5";
            ApiVersionEnum[ApiVersionEnum["V15_4"] = 25] = "V15_4";
            ApiVersionEnum[ApiVersionEnum["V15_4_1"] = 26] = "V15_4_1";
            ApiVersionEnum[ApiVersionEnum["V15_4_2"] = 27] = "V15_4_2";
            ApiVersionEnum[ApiVersionEnum["V15_4_3"] = 28] = "V15_4_3";
            ApiVersionEnum[ApiVersionEnum["V15_4_4"] = 29] = "V15_4_4";
            ApiVersionEnum[ApiVersionEnum["V15_4_5"] = 30] = "V15_4_5";
            ApiVersionEnum[ApiVersionEnum["V15_4_6"] = 31] = "V15_4_6";
            ApiVersionEnum[ApiVersionEnum["V15_4_7"] = 32] = "V15_4_7";
            ApiVersionEnum[ApiVersionEnum["V15_5"] = 33] = "V15_5";
            ApiVersionEnum[ApiVersionEnum["V15_5_1"] = 34] = "V15_5_1";
            ApiVersionEnum[ApiVersionEnum["V15_5_2"] = 35] = "V15_5_2";
            ApiVersionEnum[ApiVersionEnum["V15_5_3"] = 36] = "V15_5_3";
            ApiVersionEnum[ApiVersionEnum["V15_5_4"] = 37] = "V15_5_4";
            ApiVersionEnum[ApiVersionEnum["V15_5_5"] = 38] = "V15_5_5";
            ApiVersionEnum[ApiVersionEnum["V15_5_6"] = 39] = "V15_5_6";
            ApiVersionEnum[ApiVersionEnum["V15_5_7"] = 40] = "V15_5_7";
            ApiVersionEnum[ApiVersionEnum["V15_6"] = 41] = "V15_6";
            ApiVersionEnum[ApiVersionEnum["V15_6_1"] = 42] = "V15_6_1";
            ApiVersionEnum[ApiVersionEnum["V15_6_2"] = 43] = "V15_6_2";
            ApiVersionEnum[ApiVersionEnum["V15_6_3"] = 44] = "V15_6_3";
            ApiVersionEnum[ApiVersionEnum["V15_6_4"] = 45] = "V15_6_4";
            ApiVersionEnum[ApiVersionEnum["V16_0"] = 46] = "V16_0";
            ApiVersionEnum[ApiVersionEnum["V16_1_0"] = 47] = "V16_1_0";
            ApiVersionEnum[ApiVersionEnum["V16_1_1"] = 48] = "V16_1_1";
            ApiVersionEnum[ApiVersionEnum["V16_4_0"] = 49] = "V16_4_0";
            ApiVersionEnum[ApiVersionEnum["V16_8_0"] = 50] = "V16_8_0";
            ApiVersionEnum[ApiVersionEnum["V16_9_0"] = 51] = "V16_9_0";
            ApiVersionEnum[ApiVersionEnum["V16_10_0"] = 52] = "V16_10_0";
            ApiVersionEnum[ApiVersionEnum["V16_11_0"] = 53] = "V16_11_0";
            ApiVersionEnum[ApiVersionEnum["V16_11_2"] = 54] = "V16_11_2";
            ApiVersionEnum[ApiVersionEnum["V16_11_6"] = 55] = "V16_11_6";
            ApiVersionEnum[ApiVersionEnum["V16_13_0"] = 56] = "V16_13_0";
            ApiVersionEnum[ApiVersionEnum["V16_13_1"] = 57] = "V16_13_1";
            ApiVersionEnum[ApiVersionEnum["V16_13_2"] = 58] = "V16_13_2";
            ApiVersionEnum[ApiVersionEnum["V16_13_4"] = 59] = "V16_13_4";
            ApiVersionEnum[ApiVersionEnum["V16_13_5"] = 60] = "V16_13_5";
            ApiVersionEnum[ApiVersionEnum["V16_13_8"] = 61] = "V16_13_8";
            ApiVersionEnum[ApiVersionEnum["V16_13_10"] = 62] = "V16_13_10";
            ApiVersionEnum[ApiVersionEnum["V16_13_11"] = 63] = "V16_13_11";
            ApiVersionEnum[ApiVersionEnum["V16_14_0"] = 64] = "V16_14_0";
            ApiVersionEnum[ApiVersionEnum["V16_14_3"] = 65] = "V16_14_3";
            ApiVersionEnum[ApiVersionEnum["V16_14_4"] = 66] = "V16_14_4";
            ApiVersionEnum[ApiVersionEnum["V16_15_0"] = 67] = "V16_15_0";
            ApiVersionEnum[ApiVersionEnum["V16_17_0"] = 68] = "V16_17_0";
            ApiVersionEnum[ApiVersionEnum["V16_17_13"] = 69] = "V16_17_13";
            ApiVersionEnum[ApiVersionEnum["V16_18_0"] = 70] = "V16_18_0";
            ApiVersionEnum[ApiVersionEnum["V16_19_0"] = 71] = "V16_19_0";
            ApiVersionEnum[ApiVersionEnum["V16_20_0"] = 72] = "V16_20_0";
            ApiVersionEnum[ApiVersionEnum["V17_7_0"] = 73] = "V17_7_0";
            ApiVersionEnum[ApiVersionEnum["V17_8_0"] = 74] = "V17_8_0";
            ApiVersionEnum[ApiVersionEnum["V17_10_0"] = 75] = "V17_10_0";
            ApiVersionEnum[ApiVersionEnum["V17_12_0"] = 76] = "V17_12_0";
            ApiVersionEnum[ApiVersionEnum["V17_15_2"] = 77] = "V17_15_2";
            ApiVersionEnum[ApiVersionEnum["V17_17_0"] = 78] = "V17_17_0";
            ApiVersionEnum[ApiVersionEnum["V17_18_0"] = 79] = "V17_18_0";
            ApiVersionEnum[ApiVersionEnum["V17_20_0"] = 80] = "V17_20_0";
            ApiVersionEnum[ApiVersionEnum["V17_20_1"] = 81] = "V17_20_1";
            ApiVersionEnum[ApiVersionEnum["V17_22_0"] = 82] = "V17_22_0";
            ApiVersionEnum[ApiVersionEnum["V17_23_0"] = 83] = "V17_23_0";
            ApiVersionEnum[ApiVersionEnum["V17_24_0"] = 84] = "V17_24_0";
            ApiVersionEnum[ApiVersionEnum["V17_25_0"] = 85] = "V17_25_0";
            ApiVersionEnum[ApiVersionEnum["V17_26_0"] = 86] = "V17_26_0";
            ApiVersionEnum[ApiVersionEnum["V17_27_0"] = 87] = "V17_27_0";
            ApiVersionEnum[ApiVersionEnum["V17_27_1"] = 88] = "V17_27_1";
            ApiVersionEnum[ApiVersionEnum["V17_31_0"] = 89] = "V17_31_0";
            ApiVersionEnum[ApiVersionEnum["V17_33_0"] = 90] = "V17_33_0";
            ApiVersionEnum[ApiVersionEnum["V17_33_6"] = 91] = "V17_33_6";
            ApiVersionEnum[ApiVersionEnum["V17_34_0"] = 92] = "V17_34_0";
            ApiVersionEnum[ApiVersionEnum["V17_34_1"] = 93] = "V17_34_1";
            ApiVersionEnum[ApiVersionEnum["V17_36_0"] = 94] = "V17_36_0";
            ApiVersionEnum[ApiVersionEnum["V17_38_0"] = 95] = "V17_38_0";
            ApiVersionEnum[ApiVersionEnum["V17_42_0"] = 96] = "V17_42_0";
            ApiVersionEnum[ApiVersionEnum["V17_44_0"] = 97] = "V17_44_0";
            ApiVersionEnum[ApiVersionEnum["V17_45_0"] = 98] = "V17_45_0";
            ApiVersionEnum[ApiVersionEnum["V17_46_0"] = 99] = "V17_46_0";
            ApiVersionEnum[ApiVersionEnum["V17_47_0"] = 100] = "V17_47_0";
            ApiVersionEnum[ApiVersionEnum["V17_51_0"] = 101] = "V17_51_0";
            ApiVersionEnum[ApiVersionEnum["V17_52_0"] = 102] = "V17_52_0";
            ApiVersionEnum[ApiVersionEnum["V17_54_0"] = 103] = "V17_54_0";
            ApiVersionEnum[ApiVersionEnum["V17_57_0"] = 104] = "V17_57_0";
            ApiVersionEnum[ApiVersionEnum["V17_58_0"] = 105] = "V17_58_0";
            ApiVersionEnum[ApiVersionEnum["V17_59_0"] = 106] = "V17_59_0";
            ApiVersionEnum[ApiVersionEnum["V17_60_1"] = 107] = "V17_60_1";
            ApiVersionEnum[ApiVersionEnum["V17_61_0"] = 108] = "V17_61_0";
            ApiVersionEnum[ApiVersionEnum["V17_62_0"] = 109] = "V17_62_0";
            ApiVersionEnum[ApiVersionEnum["V17_63_0"] = 110] = "V17_63_0";
            ApiVersionEnum[ApiVersionEnum["V17_65_0"] = 111] = "V17_65_0";
            ApiVersionEnum[ApiVersionEnum["V17_69_0"] = 112] = "V17_69_0";
            ApiVersionEnum[ApiVersionEnum["V17_70_0"] = 113] = "V17_70_0";
            ApiVersionEnum[ApiVersionEnum["V17_71_0"] = 114] = "V17_71_0";
            ApiVersionEnum[ApiVersionEnum["V17_71_2"] = 115] = "V17_71_2";
            ApiVersionEnum[ApiVersionEnum["V17_73_0"] = 116] = "V17_73_0";
            ApiVersionEnum[ApiVersionEnum["V17_74_0"] = 117] = "V17_74_0";
            ApiVersionEnum[ApiVersionEnum["V17_75_0"] = 118] = "V17_75_0";
            ApiVersionEnum[ApiVersionEnum["V17_77_0"] = 119] = "V17_77_0";
            ApiVersionEnum[ApiVersionEnum["V17_78_1"] = 120] = "V17_78_1";
            ApiVersionEnum[ApiVersionEnum["V17_79_0"] = 121] = "V17_79_0";
            ApiVersionEnum[ApiVersionEnum["V17_81_0"] = 122] = "V17_81_0";
            ApiVersionEnum[ApiVersionEnum["V17_81_1"] = 123] = "V17_81_1";
            ApiVersionEnum[ApiVersionEnum["V17_83_0"] = 124] = "V17_83_0";
            ApiVersionEnum[ApiVersionEnum["V17_88_0"] = 125] = "V17_88_0";
            ApiVersionEnum[ApiVersionEnum["V17_90_1"] = 126] = "V17_90_1";
            ApiVersionEnum[ApiVersionEnum["V17_92_0"] = 127] = "V17_92_0";
            ApiVersionEnum[ApiVersionEnum["V17_94_2"] = 128] = "V17_94_2";
            ApiVersionEnum[ApiVersionEnum["V17_102_0"] = 129] = "V17_102_0";
            ApiVersionEnum[ApiVersionEnum["V17_106_0"] = 130] = "V17_106_0";
            ApiVersionEnum[ApiVersionEnum["V17_106_3"] = 131] = "V17_106_3";
            ApiVersionEnum[ApiVersionEnum["V17_107_0"] = 132] = "V17_107_0";
            ApiVersionEnum[ApiVersionEnum["V17_108_0"] = 133] = "V17_108_0";
            ApiVersionEnum[ApiVersionEnum["V17_109_0"] = 134] = "V17_109_0";
            ApiVersionEnum[ApiVersionEnum["V17_109_2"] = 135] = "V17_109_2";
        })(ApiVersionEnum = Enums.ApiVersionEnum || (Enums.ApiVersionEnum = {}));
        var ApplyLevel;
        (function (ApplyLevel) {
            ApplyLevel[ApplyLevel["Null"] = 0] = "Null";
            ApplyLevel[ApplyLevel["Domain"] = 1] = "Domain";
            ApplyLevel[ApplyLevel["Group"] = 2] = "Group";
            ApplyLevel[ApplyLevel["User"] = 3] = "User";
        })(ApplyLevel = Enums.ApplyLevel || (Enums.ApplyLevel = {}));
        var AssetAliasType;
        (function (AssetAliasType) {
            AssetAliasType[AssetAliasType["Layer"] = 0] = "Layer";
            AssetAliasType[AssetAliasType["Group"] = 1] = "Group";
        })(AssetAliasType = Enums.AssetAliasType || (Enums.AssetAliasType = {}));
        var AssetRatingMethod;
        (function (AssetRatingMethod) {
            AssetRatingMethod[AssetRatingMethod["Null"] = 0] = "Null";
            AssetRatingMethod[AssetRatingMethod["CONDITIONRATING"] = 1] = "CONDITIONRATING";
            AssetRatingMethod[AssetRatingMethod["SIDEWALKRATING"] = 2] = "SIDEWALKRATING";
            AssetRatingMethod[AssetRatingMethod["TREEDAMAGERATING"] = 3] = "TREEDAMAGERATING";
        })(AssetRatingMethod = Enums.AssetRatingMethod || (Enums.AssetRatingMethod = {}));
        var AttachmentFileType;
        (function (AttachmentFileType) {
            AttachmentFileType[AttachmentFileType["ATTACHMENT"] = 0] = "ATTACHMENT";
            AttachmentFileType[AttachmentFileType["SIGNATURE"] = 1] = "SIGNATURE";
            AttachmentFileType[AttachmentFileType["URL"] = 2] = "URL";
        })(AttachmentFileType = Enums.AttachmentFileType || (Enums.AttachmentFileType = {}));
        var AttachmentType;
        (function (AttachmentType) {
            AttachmentType[AttachmentType["None"] = 0] = "None";
            AttachmentType[AttachmentType["Contract"] = 1] = "Contract";
            AttachmentType[AttachmentType["Request"] = 2] = "Request";
            AttachmentType[AttachmentType["WorkOrder"] = 3] = "WorkOrder";
            AttachmentType[AttachmentType["Inspection"] = 4] = "Inspection";
            AttachmentType[AttachmentType["Project"] = 5] = "Project";
            AttachmentType[AttachmentType["Transaction"] = 6] = "Transaction";
            AttachmentType[AttachmentType["TvInspection"] = 7] = "TvInspection";
            AttachmentType[AttachmentType["TvObservation"] = 8] = "TvObservation";
        })(AttachmentType = Enums.AttachmentType || (Enums.AttachmentType = {}));
        var ChangeOutOp;
        (function (ChangeOutOp) {
            ChangeOutOp[ChangeOutOp["DETACH"] = 0] = "DETACH";
            ChangeOutOp[ChangeOutOp["ATTACH"] = 1] = "ATTACH";
            ChangeOutOp[ChangeOutOp["REPLACE"] = 2] = "REPLACE";
            ChangeOutOp[ChangeOutOp["NULL"] = 3] = "NULL";
            ChangeOutOp[ChangeOutOp["READ"] = 4] = "READ";
        })(ChangeOutOp = Enums.ChangeOutOp || (Enums.ChangeOutOp = {}));
        var CodeDescUsage;
        (function (CodeDescUsage) {
            CodeDescUsage[CodeDescUsage["Null"] = 0] = "Null";
            CodeDescUsage[CodeDescUsage["Code"] = 1] = "Code";
            CodeDescUsage[CodeDescUsage["Description"] = 2] = "Description";
        })(CodeDescUsage = Enums.CodeDescUsage || (Enums.CodeDescUsage = {}));
        var CommentActivityType;
        (function (CommentActivityType) {
            CommentActivityType[CommentActivityType["Unknown"] = 0] = "Unknown";
            CommentActivityType[CommentActivityType["Request"] = 1] = "Request";
            CommentActivityType[CommentActivityType["WorkOrder"] = 2] = "WorkOrder";
            CommentActivityType[CommentActivityType["CaTask"] = 3] = "CaTask";
            CommentActivityType[CommentActivityType["CaObject"] = 4] = "CaObject";
            CommentActivityType[CommentActivityType["CaCorrection"] = 5] = "CaCorrection";
            CommentActivityType[CommentActivityType["Project"] = 6] = "Project";
            CommentActivityType[CommentActivityType["Contract"] = 7] = "Contract";
            CommentActivityType[CommentActivityType["Inspection"] = 8] = "Inspection";
        })(CommentActivityType = Enums.CommentActivityType || (Enums.CommentActivityType = {}));
        var ContractorRateType;
        (function (ContractorRateType) {
            ContractorRateType[ContractorRateType["Hourly"] = 0] = "Hourly";
            ContractorRateType[ContractorRateType["Fixed"] = 1] = "Fixed";
            ContractorRateType[ContractorRateType["PerUnit"] = 2] = "PerUnit";
        })(ContractorRateType = Enums.ContractorRateType || (Enums.ContractorRateType = {}));
        var CoreResponseStatus;
        (function (CoreResponseStatus) {
            CoreResponseStatus[CoreResponseStatus["Ok"] = 0] = "Ok";
            CoreResponseStatus[CoreResponseStatus["Error"] = 1] = "Error";
            CoreResponseStatus[CoreResponseStatus["Unauthorized"] = 2] = "Unauthorized";
            CoreResponseStatus[CoreResponseStatus["InvalidCredentials"] = 3] = "InvalidCredentials";
            CoreResponseStatus[CoreResponseStatus["ConnectionError"] = -1] = "ConnectionError";
        })(CoreResponseStatus = Enums.CoreResponseStatus || (Enums.CoreResponseStatus = {}));
        var CostUsage;
        (function (CostUsage) {
            CostUsage[CostUsage["Actual"] = 0] = "Actual";
            CostUsage[CostUsage["Projected"] = 1] = "Projected";
            CostUsage[CostUsage["Template"] = 2] = "Template";
            CostUsage[CostUsage["Reported"] = 3] = "Reported";
        })(CostUsage = Enums.CostUsage || (Enums.CostUsage = {}));
        var CustomFieldValueSource;
        (function (CustomFieldValueSource) {
            CustomFieldValueSource[CustomFieldValueSource["DEFAULT"] = 0] = "DEFAULT";
            CustomFieldValueSource[CustomFieldValueSource["PARENTWO"] = 1] = "PARENTWO";
        })(CustomFieldValueSource = Enums.CustomFieldValueSource || (Enums.CustomFieldValueSource = {}));
        var CWEntityType;
        (function (CWEntityType) {
            CWEntityType[CWEntityType["Null"] = 0] = "Null";
            CWEntityType[CWEntityType["Feature"] = 1] = "Feature";
            CWEntityType[CWEntityType["Object"] = 2] = "Object";
            CWEntityType[CWEntityType["Other"] = 3] = "Other";
        })(CWEntityType = Enums.CWEntityType || (Enums.CWEntityType = {}));
        var DashboardAggregationType;
        (function (DashboardAggregationType) {
            DashboardAggregationType[DashboardAggregationType["Null"] = 0] = "Null";
            DashboardAggregationType[DashboardAggregationType["Count"] = 1] = "Count";
            DashboardAggregationType[DashboardAggregationType["Sum"] = 2] = "Sum";
            DashboardAggregationType[DashboardAggregationType["Average"] = 3] = "Average";
        })(DashboardAggregationType = Enums.DashboardAggregationType || (Enums.DashboardAggregationType = {}));
        var DashboardChartWidgetType;
        (function (DashboardChartWidgetType) {
            DashboardChartWidgetType[DashboardChartWidgetType["Null"] = 0] = "Null";
            DashboardChartWidgetType[DashboardChartWidgetType["Pie"] = 1] = "Pie";
            DashboardChartWidgetType[DashboardChartWidgetType["Bar"] = 2] = "Bar";
            DashboardChartWidgetType[DashboardChartWidgetType["Line"] = 3] = "Line";
            DashboardChartWidgetType[DashboardChartWidgetType["HorizBar"] = 4] = "HorizBar";
        })(DashboardChartWidgetType = Enums.DashboardChartWidgetType || (Enums.DashboardChartWidgetType = {}));
        var DashboardNumberFormat;
        (function (DashboardNumberFormat) {
            DashboardNumberFormat[DashboardNumberFormat["Null"] = 0] = "Null";
            DashboardNumberFormat[DashboardNumberFormat["Numeric"] = 1] = "Numeric";
            DashboardNumberFormat[DashboardNumberFormat["Currency"] = 2] = "Currency";
            DashboardNumberFormat[DashboardNumberFormat["Percent"] = 3] = "Percent";
        })(DashboardNumberFormat = Enums.DashboardNumberFormat || (Enums.DashboardNumberFormat = {}));
        var DateGroupByOption;
        (function (DateGroupByOption) {
            DateGroupByOption[DateGroupByOption["Day"] = 0] = "Day";
            DateGroupByOption[DateGroupByOption["Week"] = 1] = "Week";
            DateGroupByOption[DateGroupByOption["Month"] = 2] = "Month";
            DateGroupByOption[DateGroupByOption["Year"] = 3] = "Year";
            DateGroupByOption[DateGroupByOption["DayOfWeek"] = 4] = "DayOfWeek";
            DateGroupByOption[DateGroupByOption["MonthOfYear"] = 5] = "MonthOfYear";
            DateGroupByOption[DateGroupByOption["DayOfYear"] = 6] = "DayOfYear";
            DateGroupByOption[DateGroupByOption["HourOfDay"] = 7] = "HourOfDay";
            DateGroupByOption[DateGroupByOption["Hour"] = 8] = "Hour";
            DateGroupByOption[DateGroupByOption["Quarter"] = 9] = "Quarter";
            DateGroupByOption[DateGroupByOption["QuarterOfYear"] = 10] = "QuarterOfYear";
        })(DateGroupByOption = Enums.DateGroupByOption || (Enums.DateGroupByOption = {}));
        var DateSelection;
        (function (DateSelection) {
            DateSelection[DateSelection["Null"] = 0] = "Null";
            DateSelection[DateSelection["Exact"] = 1] = "Exact";
            DateSelection[DateSelection["Relative"] = 2] = "Relative";
        })(DateSelection = Enums.DateSelection || (Enums.DateSelection = {}));
        var DayOfWeek;
        (function (DayOfWeek) {
            DayOfWeek[DayOfWeek["Sunday"] = 0] = "Sunday";
            DayOfWeek[DayOfWeek["Monday"] = 1] = "Monday";
            DayOfWeek[DayOfWeek["Tuesday"] = 2] = "Tuesday";
            DayOfWeek[DayOfWeek["Wednesday"] = 3] = "Wednesday";
            DayOfWeek[DayOfWeek["Thursday"] = 4] = "Thursday";
            DayOfWeek[DayOfWeek["Friday"] = 5] = "Friday";
            DayOfWeek[DayOfWeek["Saturday"] = 6] = "Saturday";
        })(DayOfWeek = Enums.DayOfWeek || (Enums.DayOfWeek = {}));
        var DistressSeverity;
        (function (DistressSeverity) {
            DistressSeverity[DistressSeverity["L"] = 0] = "L";
            DistressSeverity[DistressSeverity["M"] = 1] = "M";
            DistressSeverity[DistressSeverity["H"] = 2] = "H";
            DistressSeverity[DistressSeverity["NA"] = 3] = "NA";
        })(DistressSeverity = Enums.DistressSeverity || (Enums.DistressSeverity = {}));
        var DocumentActivityType;
        (function (DocumentActivityType) {
            DocumentActivityType[DocumentActivityType["Case"] = 0] = "Case";
            DocumentActivityType[DocumentActivityType["Task"] = 1] = "Task";
            DocumentActivityType[DocumentActivityType["Payment"] = 2] = "Payment";
        })(DocumentActivityType = Enums.DocumentActivityType || (Enums.DocumentActivityType = {}));
        var EquipChangeOutType;
        (function (EquipChangeOutType) {
            EquipChangeOutType[EquipChangeOutType["AddRelationship"] = 0] = "AddRelationship";
            EquipChangeOutType[EquipChangeOutType["ModifyRelationship"] = 1] = "ModifyRelationship";
            EquipChangeOutType[EquipChangeOutType["DissolveRelationship"] = 2] = "DissolveRelationship";
            EquipChangeOutType[EquipChangeOutType["Unknown"] = 3] = "Unknown";
        })(EquipChangeOutType = Enums.EquipChangeOutType || (Enums.EquipChangeOutType = {}));
        var EquipmentRateType;
        (function (EquipmentRateType) {
            EquipmentRateType[EquipmentRateType["Hourly"] = 0] = "Hourly";
            EquipmentRateType[EquipmentRateType["Fixed"] = 1] = "Fixed";
        })(EquipmentRateType = Enums.EquipmentRateType || (Enums.EquipmentRateType = {}));
        var EquipTransType;
        (function (EquipTransType) {
            EquipTransType[EquipTransType["IN"] = 0] = "IN";
            EquipTransType[EquipTransType["OUT"] = 1] = "OUT";
            EquipTransType[EquipTransType["RESERVED"] = 2] = "RESERVED";
            EquipTransType[EquipTransType["NULL"] = 3] = "NULL";
        })(EquipTransType = Enums.EquipTransType || (Enums.EquipTransType = {}));
        var EventSourceType;
        (function (EventSourceType) {
            EventSourceType[EventSourceType["Request"] = 0] = "Request";
            EventSourceType[EventSourceType["WorkOrder"] = 1] = "WorkOrder";
            EventSourceType[EventSourceType["Inspection"] = 2] = "Inspection";
            EventSourceType[EventSourceType["Permit"] = 3] = "Permit";
            EventSourceType[EventSourceType["Comment"] = 4] = "Comment";
            EventSourceType[EventSourceType["WorkOrderLabor"] = 5] = "WorkOrderLabor";
            EventSourceType[EventSourceType["RequestLabor"] = 6] = "RequestLabor";
            EventSourceType[EventSourceType["Unknown"] = 7] = "Unknown";
            EventSourceType[EventSourceType["SMS"] = 8] = "SMS";
            EventSourceType[EventSourceType["CaTaskItem"] = 9] = "CaTaskItem";
            EventSourceType[EventSourceType["WoTask"] = 10] = "WoTask";
            EventSourceType[EventSourceType["RequestAttachment"] = 11] = "RequestAttachment";
            EventSourceType[EventSourceType["WorkOrderAttachment"] = 12] = "WorkOrderAttachment";
            EventSourceType[EventSourceType["InspectionAttachment"] = 13] = "InspectionAttachment";
            EventSourceType[EventSourceType["CaRelDocs"] = 14] = "CaRelDocs";
            EventSourceType[EventSourceType["InspectionLabor"] = 15] = "InspectionLabor";
            EventSourceType[EventSourceType["InspectionEquipment"] = 16] = "InspectionEquipment";
            EventSourceType[EventSourceType["WorkOrderEquipment"] = 17] = "WorkOrderEquipment";
            EventSourceType[EventSourceType["WorkOrderMaterial"] = 18] = "WorkOrderMaterial";
            EventSourceType[EventSourceType["RequestCaller"] = 19] = "RequestCaller";
            EventSourceType[EventSourceType["CaAddressItem"] = 20] = "CaAddressItem";
            EventSourceType[EventSourceType["CaFeesItem"] = 21] = "CaFeesItem";
            EventSourceType[EventSourceType["Projects"] = 22] = "Projects";
            EventSourceType[EventSourceType["ProjectAttachment"] = 23] = "ProjectAttachment";
            EventSourceType[EventSourceType["ContractAttachment"] = 24] = "ContractAttachment";
        })(EventSourceType = Enums.EventSourceType || (Enums.EventSourceType = {}));
        var EventTriggerType;
        (function (EventTriggerType) {
            EventTriggerType[EventTriggerType["Always"] = 0] = "Always";
            EventTriggerType[EventTriggerType["Equal"] = 1] = "Equal";
            EventTriggerType[EventTriggerType["NotEqual"] = 2] = "NotEqual";
            EventTriggerType[EventTriggerType["LessThan"] = 3] = "LessThan";
            EventTriggerType[EventTriggerType["GreaterThan"] = 4] = "GreaterThan";
            EventTriggerType[EventTriggerType["Contains"] = 5] = "Contains";
            EventTriggerType[EventTriggerType["NotContains"] = 6] = "NotContains";
            EventTriggerType[EventTriggerType["NullOrEmpty"] = 7] = "NullOrEmpty";
            EventTriggerType[EventTriggerType["NotNullOrEmpty"] = 8] = "NotNullOrEmpty";
            EventTriggerType[EventTriggerType["Unknown"] = 9] = "Unknown";
        })(EventTriggerType = Enums.EventTriggerType || (Enums.EventTriggerType = {}));
        var FieldDataType;
        (function (FieldDataType) {
            FieldDataType[FieldDataType["VARCHAR"] = 0] = "VARCHAR";
            FieldDataType[FieldDataType["NUMERIC"] = 1] = "NUMERIC";
            FieldDataType[FieldDataType["DATE"] = 2] = "DATE";
        })(FieldDataType = Enums.FieldDataType || (Enums.FieldDataType = {}));
        var GISRight;
        (function (GISRight) {
            GISRight[GISRight["View"] = 0] = "View";
            GISRight[GISRight["Attribute"] = 1] = "Attribute";
            GISRight[GISRight["Geometry"] = 2] = "Geometry";
        })(GISRight = Enums.GISRight || (Enums.GISRight = {}));
        var GISServiceSecurityType;
        (function (GISServiceSecurityType) {
            GISServiceSecurityType[GISServiceSecurityType["NONE"] = 0] = "NONE";
            GISServiceSecurityType[GISServiceSecurityType["GENERATETOKEN"] = 1] = "GENERATETOKEN";
            GISServiceSecurityType[GISServiceSecurityType["OAUTHUSER"] = 2] = "OAUTHUSER";
            GISServiceSecurityType[GISServiceSecurityType["OAUTHAPP"] = 3] = "OAUTHAPP";
        })(GISServiceSecurityType = Enums.GISServiceSecurityType || (Enums.GISServiceSecurityType = {}));
        var GISServiceType;
        (function (GISServiceType) {
            GISServiceType[GISServiceType["DYNAMICMAP"] = 0] = "DYNAMICMAP";
            GISServiceType[GISServiceType["TILEDMAP"] = 1] = "TILEDMAP";
            GISServiceType[GISServiceType["IMAGEMAP"] = 2] = "IMAGEMAP";
            GISServiceType[GISServiceType["GEOCODE"] = 3] = "GEOCODE";
            GISServiceType[GISServiceType["GEOMETRY"] = 4] = "GEOMETRY";
            GISServiceType[GISServiceType["FEATURELAYER"] = 5] = "FEATURELAYER";
            GISServiceType[GISServiceType["WEBMAP"] = 6] = "WEBMAP";
            GISServiceType[GISServiceType["HEATMAP"] = 7] = "HEATMAP";
            GISServiceType[GISServiceType["KMLLAYER"] = 8] = "KMLLAYER";
            GISServiceType[GISServiceType["WMSLAYER"] = 9] = "WMSLAYER";
            GISServiceType[GISServiceType["GEODATA"] = 10] = "GEODATA";
            GISServiceType[GISServiceType["SOE"] = 11] = "SOE";
            GISServiceType[GISServiceType["UNKNOWN"] = 12] = "UNKNOWN";
            GISServiceType[GISServiceType["RESOURCEPROXY"] = 13] = "RESOURCEPROXY";
            GISServiceType[GISServiceType["TILEPACKAGE"] = 14] = "TILEPACKAGE";
            GISServiceType[GISServiceType["PRINTING"] = 15] = "PRINTING";
            GISServiceType[GISServiceType["ROUTING"] = 16] = "ROUTING";
            GISServiceType[GISServiceType["VECTORTILE"] = 17] = "VECTORTILE";
            GISServiceType[GISServiceType["MOBILEMAPPACKAGE"] = 18] = "MOBILEMAPPACKAGE";
            GISServiceType[GISServiceType["WEBSCENE"] = 19] = "WEBSCENE";
        })(GISServiceType = Enums.GISServiceType || (Enums.GISServiceType = {}));
        var InspQuestionType;
        (function (InspQuestionType) {
            InspQuestionType[InspQuestionType["Single"] = 0] = "Single";
            InspQuestionType[InspQuestionType["Multiple"] = 1] = "Multiple";
            InspQuestionType[InspQuestionType["Assets"] = 2] = "Assets";
        })(InspQuestionType = Enums.InspQuestionType || (Enums.InspQuestionType = {}));
        var IsActiveStatus;
        (function (IsActiveStatus) {
            IsActiveStatus[IsActiveStatus["Active"] = 0] = "Active";
            IsActiveStatus[IsActiveStatus["Inactive"] = 1] = "Inactive";
            IsActiveStatus[IsActiveStatus["All"] = 2] = "All";
        })(IsActiveStatus = Enums.IsActiveStatus || (Enums.IsActiveStatus = {}));
        var LaborCategory;
        (function (LaborCategory) {
            LaborCategory[LaborCategory["Employee"] = 0] = "Employee";
            LaborCategory[LaborCategory["Contractor"] = 1] = "Contractor";
        })(LaborCategory = Enums.LaborCategory || (Enums.LaborCategory = {}));
        var LaborRateType;
        (function (LaborRateType) {
            LaborRateType[LaborRateType["Hourly"] = 0] = "Hourly";
            LaborRateType[LaborRateType["Overtime"] = 1] = "Overtime";
            LaborRateType[LaborRateType["Emergency"] = 2] = "Emergency";
            LaborRateType[LaborRateType["Fixed"] = 3] = "Fixed";
            LaborRateType[LaborRateType["PerUnit"] = 4] = "PerUnit";
        })(LaborRateType = Enums.LaborRateType || (Enums.LaborRateType = {}));
        var LicensedExtension;
        (function (LicensedExtension) {
            LicensedExtension[LicensedExtension["UnknownExtension"] = 0] = "UnknownExtension";
            LicensedExtension[LicensedExtension["CwAnalytics"] = 1] = "CwAnalytics";
            LicensedExtension[LicensedExtension["WebHooks"] = 2] = "WebHooks";
            LicensedExtension[LicensedExtension["PLLPublicApp"] = 3] = "PLLPublicApp";
            LicensedExtension[LicensedExtension["ActivityUpdate"] = 4] = "ActivityUpdate";
            LicensedExtension[LicensedExtension["SingleSignOn"] = 5] = "SingleSignOn";
        })(LicensedExtension = Enums.LicensedExtension || (Enums.LicensedExtension = {}));
        var LicensedFeature;
        (function (LicensedFeature) {
            LicensedFeature[LicensedFeature["UnknownFeature"] = 0] = "UnknownFeature";
            LicensedFeature[LicensedFeature["ViewInspections"] = 1] = "ViewInspections";
            LicensedFeature[LicensedFeature["EditInspections"] = 2] = "EditInspections";
            LicensedFeature[LicensedFeature["ViewServiceRequest"] = 3] = "ViewServiceRequest";
            LicensedFeature[LicensedFeature["EditServiceRequest"] = 4] = "EditServiceRequest";
            LicensedFeature[LicensedFeature["ViewWorkOrder"] = 5] = "ViewWorkOrder";
            LicensedFeature[LicensedFeature["EditWorkOrder"] = 6] = "EditWorkOrder";
            LicensedFeature[LicensedFeature["EquipmentCheckOut"] = 7] = "EquipmentCheckOut";
            LicensedFeature[LicensedFeature["OfficeField"] = 8] = "OfficeField";
            LicensedFeature[LicensedFeature["Respond"] = 9] = "Respond";
            LicensedFeature[LicensedFeature["Eurl"] = 10] = "Eurl";
            LicensedFeature[LicensedFeature["PaverInterface"] = 11] = "PaverInterface";
            LicensedFeature[LicensedFeature["Contracts"] = 12] = "Contracts";
            LicensedFeature[LicensedFeature["Storeroom"] = 13] = "Storeroom";
            LicensedFeature[LicensedFeature["PLL"] = 14] = "PLL";
            LicensedFeature[LicensedFeature["Cw4XL"] = 15] = "Cw4XL";
            LicensedFeature[LicensedFeature["TableEditor"] = 16] = "TableEditor";
            LicensedFeature[LicensedFeature["CCTVInterface"] = 17] = "CCTVInterface";
            LicensedFeature[LicensedFeature["MobileAndroid"] = 18] = "MobileAndroid";
            LicensedFeature[LicensedFeature["MobileiOS"] = 19] = "MobileiOS";
            LicensedFeature[LicensedFeature["PerformanceBudgeting"] = 20] = "PerformanceBudgeting";
            LicensedFeature[LicensedFeature["Insights"] = 21] = "Insights";
            LicensedFeature[LicensedFeature["RespondCase"] = 22] = "RespondCase";
            LicensedFeature[LicensedFeature["RespondInspection"] = 23] = "RespondInspection";
            LicensedFeature[LicensedFeature["RespondServiceRequest"] = 24] = "RespondServiceRequest";
            LicensedFeature[LicensedFeature["RespondTaskManager"] = 25] = "RespondTaskManager";
            LicensedFeature[LicensedFeature["RespondWorkOrder"] = 26] = "RespondWorkOrder";
            LicensedFeature[LicensedFeature["Workload"] = 27] = "Workload";
            LicensedFeature[LicensedFeature["OpX"] = 28] = "OpX";
            LicensedFeature[LicensedFeature["TrimbleUnityMobile"] = 29] = "TrimbleUnityMobile";
            LicensedFeature[LicensedFeature["TrimbleVegetationManager"] = 30] = "TrimbleVegetationManager";
        })(LicensedFeature = Enums.LicensedFeature || (Enums.LicensedFeature = {}));
        var MaterialCostType;
        (function (MaterialCostType) {
            MaterialCostType[MaterialCostType["AVERAGE"] = 1] = "AVERAGE";
            MaterialCostType[MaterialCostType["CURRENT"] = 2] = "CURRENT";
            MaterialCostType[MaterialCostType["FIFO"] = 3] = "FIFO";
            MaterialCostType[MaterialCostType["LIFO"] = 4] = "LIFO";
            MaterialCostType[MaterialCostType["SERIAL"] = 5] = "SERIAL";
        })(MaterialCostType = Enums.MaterialCostType || (Enums.MaterialCostType = {}));
        var NativeAppWorkActivityType;
        (function (NativeAppWorkActivityType) {
            NativeAppWorkActivityType[NativeAppWorkActivityType["Case"] = 1] = "Case";
            NativeAppWorkActivityType[NativeAppWorkActivityType["Inspection"] = 2] = "Inspection";
            NativeAppWorkActivityType[NativeAppWorkActivityType["ServiceRequest"] = 3] = "ServiceRequest";
            NativeAppWorkActivityType[NativeAppWorkActivityType["WorkOrder"] = 4] = "WorkOrder";
        })(NativeAppWorkActivityType = Enums.NativeAppWorkActivityType || (Enums.NativeAppWorkActivityType = {}));
        var NotificationActivityType;
        (function (NotificationActivityType) {
            NotificationActivityType[NotificationActivityType["Null"] = 0] = "Null";
            NotificationActivityType[NotificationActivityType["Case"] = 1] = "Case";
            NotificationActivityType[NotificationActivityType["CaseTask"] = 2] = "CaseTask";
        })(NotificationActivityType = Enums.NotificationActivityType || (Enums.NotificationActivityType = {}));
        var NotificationEventType;
        (function (NotificationEventType) {
            NotificationEventType[NotificationEventType["Null"] = 0] = "Null";
            NotificationEventType[NotificationEventType["CommentMention"] = 1] = "CommentMention";
            NotificationEventType[NotificationEventType["AttachmentAdded"] = 2] = "AttachmentAdded";
            NotificationEventType[NotificationEventType["PaymentMade"] = 3] = "PaymentMade";
            NotificationEventType[NotificationEventType["AllFeesPaid"] = 4] = "AllFeesPaid";
        })(NotificationEventType = Enums.NotificationEventType || (Enums.NotificationEventType = {}));
        var NumericValueMode;
        (function (NumericValueMode) {
            NumericValueMode[NumericValueMode["Nulls"] = 0] = "Nulls";
            NumericValueMode[NumericValueMode["MinMax"] = 1] = "MinMax";
            NumericValueMode[NumericValueMode["ListOfValues"] = 2] = "ListOfValues";
            NumericValueMode[NumericValueMode["NotListOfValues"] = 3] = "NotListOfValues";
            NumericValueMode[NumericValueMode["Disjoint"] = 4] = "Disjoint";
            NumericValueMode[NumericValueMode["Invalid"] = 5] = "Invalid";
            NumericValueMode[NumericValueMode["NotNull"] = 6] = "NotNull";
        })(NumericValueMode = Enums.NumericValueMode || (Enums.NumericValueMode = {}));
        var PacpMappingDirection;
        (function (PacpMappingDirection) {
            PacpMappingDirection[PacpMappingDirection["Export"] = 0] = "Export";
            PacpMappingDirection[PacpMappingDirection["Import"] = 1] = "Import";
            PacpMappingDirection[PacpMappingDirection["ExportImport"] = 2] = "ExportImport";
        })(PacpMappingDirection = Enums.PacpMappingDirection || (Enums.PacpMappingDirection = {}));
        var PipeInOut;
        (function (PipeInOut) {
            PipeInOut[PipeInOut["I"] = 0] = "I";
            PipeInOut[PipeInOut["O"] = 1] = "O";
        })(PipeInOut = Enums.PipeInOut || (Enums.PipeInOut = {}));
        var PWCodeType;
        (function (PWCodeType) {
            PWCodeType[PWCodeType["ACTGCODE"] = 0] = "ACTGCODE";
            PWCodeType[PWCodeType["ACTPAVDP"] = 1] = "ACTPAVDP";
            PWCodeType[PWCodeType["ACTPCODE"] = 2] = "ACTPCODE";
            PWCodeType[PWCodeType["ACTPELEV"] = 3] = "ACTPELEV";
            PWCodeType[PWCodeType["ACTPINVT"] = 4] = "ACTPINVT";
            PWCodeType[PWCodeType["ACTPMGTU"] = 5] = "ACTPMGTU";
            PWCodeType[PWCodeType["ACTPPRGC"] = 6] = "ACTPPRGC";
            PWCodeType[PWCodeType["ACTPWKQD"] = 7] = "ACTPWKQD";
            PWCodeType[PWCodeType["ACALLTYP"] = 8] = "ACALLTYP";
            PWCodeType[PWCodeType["ACALLTITLE"] = 9] = "ACALLTITLE";
            PWCodeType[PWCodeType["ACREWCAT"] = 10] = "ACREWCAT";
            PWCodeType[PWCodeType["ADISTRCT"] = 11] = "ADISTRCT";
            PWCodeType[PWCodeType["ALNDMARK"] = 12] = "ALNDMARK";
            PWCodeType[PWCodeType["AMATCAT"] = 13] = "AMATCAT";
            PWCodeType[PWCodeType["APRIORIT"] = 14] = "APRIORIT";
            PWCodeType[PWCodeType["APROBCAT"] = 15] = "APROBCAT";
            PWCodeType[PWCodeType["APSOURCE"] = 16] = "APSOURCE";
            PWCodeType[PWCodeType["ATSKSTAT"] = 17] = "ATSKSTAT";
            PWCodeType[PWCodeType["AWOCAT"] = 18] = "AWOCAT";
            PWCodeType[PWCodeType["GLACCOUNT"] = 19] = "GLACCOUNT";
            PWCodeType[PWCodeType["INSPRESO"] = 20] = "INSPRESO";
            PWCodeType[PWCodeType["INSPSTAT"] = 21] = "INSPSTAT";
            PWCodeType[PWCodeType["INSPPRINT"] = 22] = "INSPPRINT";
            PWCodeType[PWCodeType["PADDTYPE"] = 23] = "PADDTYPE";
            PWCodeType[PWCodeType["PMTSTAT"] = 24] = "PMTSTAT";
            PWCodeType[PWCodeType["SHOP"] = 25] = "SHOP";
            PWCodeType[PWCodeType["SRRESO"] = 26] = "SRRESO";
            PWCodeType[PWCodeType["SRSTATUS"] = 27] = "SRSTATUS";
            PWCodeType[PWCodeType["UACCDESC"] = 28] = "UACCDESC";
            PWCodeType[PWCodeType["WORESO"] = 29] = "WORESO";
            PWCodeType[PWCodeType["WOSTATUS"] = 30] = "WOSTATUS";
            PWCodeType[PWCodeType["WOPRINT"] = 31] = "WOPRINT";
            PWCodeType[PWCodeType["STORERM"] = 32] = "STORERM";
            PWCodeType[PWCodeType["CONSTAT"] = 33] = "CONSTAT";
            PWCodeType[PWCodeType["CONTRACTPHASE"] = 34] = "CONTRACTPHASE";
            PWCodeType[PWCodeType["CONTSUBMITTYPE"] = 35] = "CONTSUBMITTYPE";
            PWCodeType[PWCodeType["CONTTYPE"] = 36] = "CONTTYPE";
            PWCodeType[PWCodeType["AEMPSKIL"] = 37] = "AEMPSKIL";
            PWCodeType[PWCodeType["CONTFUND"] = 38] = "CONTFUND";
            PWCodeType[PWCodeType["TECHUSED"] = 39] = "TECHUSED";
            PWCodeType[PWCodeType["FLWCONTRL"] = 40] = "FLWCONTRL";
            PWCodeType[PWCodeType["PACPINSTAT"] = 41] = "PACPINSTAT";
            PWCodeType[PWCodeType["PIPEUSE"] = 42] = "PIPEUSE";
            PWCodeType[PWCodeType["PRJTSTAT"] = 43] = "PRJTSTAT";
            PWCodeType[PWCodeType["SSHAPE"] = 44] = "SSHAPE";
            PWCodeType[PWCodeType["CTMETHOD"] = 45] = "CTMETHOD";
            PWCodeType[PWCodeType["PRECLEAN"] = 46] = "PRECLEAN";
            PWCodeType[PWCodeType["WEATHER"] = 47] = "WEATHER";
            PWCodeType[PWCodeType["LOCATIONCODE"] = 48] = "LOCATIONCODE";
            PWCodeType[PWCodeType["PROJECTCAT"] = 49] = "PROJECTCAT";
            PWCodeType[PWCodeType["ACCOUNT"] = 50] = "ACCOUNT";
            PWCodeType[PWCodeType["REQPRINT"] = 51] = "REQPRINT";
            PWCodeType[PWCodeType["UNITMEAS"] = 52] = "UNITMEAS";
            PWCodeType[PWCodeType["CONTRACTCAT"] = 53] = "CONTRACTCAT";
            PWCodeType[PWCodeType["SDAREA"] = 54] = "SDAREA";
            PWCodeType[PWCodeType["SLMETHOD"] = 55] = "SLMETHOD";
            PWCodeType[PWCodeType["SPIPEMT"] = 56] = "SPIPEMT";
            PWCodeType[PWCodeType["STVREASN"] = 57] = "STVREASN";
            PWCodeType[PWCodeType["SMHPART"] = 58] = "SMHPART";
            PWCodeType[PWCodeType["SACCESS"] = 59] = "SACCESS";
            PWCodeType[PWCodeType["SBNCHMT"] = 60] = "SBNCHMT";
            PWCodeType[PWCodeType["SCHANLMT"] = 61] = "SCHANLMT";
            PWCodeType[PWCodeType["SCONEMT"] = 62] = "SCONEMT";
            PWCodeType[PWCodeType["SFRAMEMT"] = 63] = "SFRAMEMT";
            PWCodeType[PWCodeType["SLIDMT"] = 64] = "SLIDMT";
            PWCodeType[PWCodeType["SBRLMT"] = 65] = "SBRLMT";
            PWCodeType[PWCodeType["SRING"] = 66] = "SRING";
            PWCodeType[PWCodeType["SSTEPMT"] = 67] = "SSTEPMT";
            PWCodeType[PWCodeType["SMHTYPE"] = 68] = "SMHTYPE";
            PWCodeType[PWCodeType["SSURFC"] = 69] = "SSURFC";
        })(PWCodeType = Enums.PWCodeType || (Enums.PWCodeType = {}));
        var QASequenceModel;
        (function (QASequenceModel) {
            QASequenceModel[QASequenceModel["Null"] = 0] = "Null";
            QASequenceModel[QASequenceModel["Linear"] = 1] = "Linear";
            QASequenceModel[QASequenceModel["Branch"] = 2] = "Branch";
        })(QASequenceModel = Enums.QASequenceModel || (Enums.QASequenceModel = {}));
        var QuestAnswerFormat;
        (function (QuestAnswerFormat) {
            QuestAnswerFormat[QuestAnswerFormat["THISTEXT"] = 0] = "THISTEXT";
            QuestAnswerFormat[QuestAnswerFormat["DATE"] = 1] = "DATE";
            QuestAnswerFormat[QuestAnswerFormat["YES"] = 2] = "YES";
            QuestAnswerFormat[QuestAnswerFormat["NO"] = 3] = "NO";
            QuestAnswerFormat[QuestAnswerFormat["UNKNOWN"] = 4] = "UNKNOWN";
            QuestAnswerFormat[QuestAnswerFormat["FREETEXT"] = 5] = "FREETEXT";
            QuestAnswerFormat[QuestAnswerFormat["CHECKED"] = 6] = "CHECKED";
            QuestAnswerFormat[QuestAnswerFormat["UNCHECK"] = 7] = "UNCHECK";
            QuestAnswerFormat[QuestAnswerFormat["CODEDESC"] = 8] = "CODEDESC";
            QuestAnswerFormat[QuestAnswerFormat["DESCSCORE"] = 9] = "DESCSCORE";
            QuestAnswerFormat[QuestAnswerFormat["CALCULATED"] = 10] = "CALCULATED";
            QuestAnswerFormat[QuestAnswerFormat["NUMERIC"] = 11] = "NUMERIC";
        })(QuestAnswerFormat = Enums.QuestAnswerFormat || (Enums.QuestAnswerFormat = {}));
        var QueueStatus;
        (function (QueueStatus) {
            QueueStatus[QueueStatus["Pending"] = 0] = "Pending";
            QueueStatus[QueueStatus["Processing"] = 1] = "Processing";
            QueueStatus[QueueStatus["Complete"] = 2] = "Complete";
            QueueStatus[QueueStatus["Failed"] = 3] = "Failed";
        })(QueueStatus = Enums.QueueStatus || (Enums.QueueStatus = {}));
        var RateAddMethod;
        (function (RateAddMethod) {
            RateAddMethod[RateAddMethod["Percent"] = 0] = "Percent";
            RateAddMethod[RateAddMethod["Fixed"] = 1] = "Fixed";
        })(RateAddMethod = Enums.RateAddMethod || (Enums.RateAddMethod = {}));
        var ReadingActionType;
        (function (ReadingActionType) {
            ReadingActionType[ReadingActionType["Null"] = 0] = "Null";
            ReadingActionType[ReadingActionType["Interval"] = 1] = "Interval";
            ReadingActionType[ReadingActionType["Milestone"] = 2] = "Milestone";
            ReadingActionType[ReadingActionType["Threshold"] = 3] = "Threshold";
        })(ReadingActionType = Enums.ReadingActionType || (Enums.ReadingActionType = {}));
        var RelativeDate;
        (function (RelativeDate) {
            RelativeDate[RelativeDate["Null"] = 0] = "Null";
            RelativeDate[RelativeDate["Next"] = 1] = "Next";
            RelativeDate[RelativeDate["Last"] = 2] = "Last";
            RelativeDate[RelativeDate["Current"] = 3] = "Current";
            RelativeDate[RelativeDate["Range"] = 4] = "Range";
        })(RelativeDate = Enums.RelativeDate || (Enums.RelativeDate = {}));
        var RelativeDateUnit;
        (function (RelativeDateUnit) {
            RelativeDateUnit[RelativeDateUnit["Null"] = 0] = "Null";
            RelativeDateUnit[RelativeDateUnit["Minutes"] = 1] = "Minutes";
            RelativeDateUnit[RelativeDateUnit["Hours"] = 2] = "Hours";
            RelativeDateUnit[RelativeDateUnit["Days"] = 3] = "Days";
            RelativeDateUnit[RelativeDateUnit["Weeks"] = 4] = "Weeks";
            RelativeDateUnit[RelativeDateUnit["Months"] = 5] = "Months";
            RelativeDateUnit[RelativeDateUnit["Years"] = 6] = "Years";
        })(RelativeDateUnit = Enums.RelativeDateUnit || (Enums.RelativeDateUnit = {}));
        var RepeatFromDate;
        (function (RepeatFromDate) {
            RepeatFromDate[RepeatFromDate["ADATE"] = 0] = "ADATE";
            RepeatFromDate[RepeatFromDate["PROJSTARTDATE"] = 1] = "PROJSTARTDATE";
            RepeatFromDate[RepeatFromDate["ACTUALFINISHDATE"] = 2] = "ACTUALFINISHDATE";
        })(RepeatFromDate = Enums.RepeatFromDate || (Enums.RepeatFromDate = {}));
        var RepeatIntervalUnit;
        (function (RepeatIntervalUnit) {
            RepeatIntervalUnit[RepeatIntervalUnit["D"] = 0] = "D";
            RepeatIntervalUnit[RepeatIntervalUnit["W"] = 1] = "W";
            RepeatIntervalUnit[RepeatIntervalUnit["M"] = 2] = "M";
            RepeatIntervalUnit[RepeatIntervalUnit["Y"] = 3] = "Y";
        })(RepeatIntervalUnit = Enums.RepeatIntervalUnit || (Enums.RepeatIntervalUnit = {}));
        var RepeatType;
        (function (RepeatType) {
            RepeatType[RepeatType["NEVER"] = 0] = "NEVER";
            RepeatType[RepeatType["ONCE"] = 1] = "ONCE";
            RepeatType[RepeatType["EVERY"] = 2] = "EVERY";
        })(RepeatType = Enums.RepeatType || (Enums.RepeatType = {}));
        var SearchType;
        (function (SearchType) {
            SearchType[SearchType["Null"] = 0] = "Null";
            SearchType[SearchType["Request"] = 1] = "Request";
            SearchType[SearchType["WorkOrder"] = 2] = "WorkOrder";
            SearchType[SearchType["Inspection"] = 3] = "Inspection";
            SearchType[SearchType["Contract"] = 4] = "Contract";
            SearchType[SearchType["Permit"] = 5] = "Permit";
            SearchType[SearchType["GIS"] = 6] = "GIS";
            SearchType[SearchType["PermitTask"] = 7] = "PermitTask";
            SearchType[SearchType["PermitAddress"] = 8] = "PermitAddress";
            SearchType[SearchType["InspCommon"] = 9] = "InspCommon";
            SearchType[SearchType["Case"] = 10] = "Case";
            SearchType[SearchType["WorkOrderEntity"] = 11] = "WorkOrderEntity";
            SearchType[SearchType["StoreTransaction"] = 12] = "StoreTransaction";
            SearchType[SearchType["Requisition"] = 13] = "Requisition";
            SearchType[SearchType["Material"] = 14] = "Material";
            SearchType[SearchType["WorkActivity"] = 15] = "WorkActivity";
            SearchType[SearchType["MaterialLeaf"] = 16] = "MaterialLeaf";
            SearchType[SearchType["WoTemplate"] = 17] = "WoTemplate";
            SearchType[SearchType["Unknown"] = 18] = "Unknown";
            SearchType[SearchType["Employee"] = 19] = "Employee";
            SearchType[SearchType["MessageQueue"] = 20] = "MessageQueue";
            SearchType[SearchType["Analytics"] = 21] = "Analytics";
            SearchType[SearchType["TokenState"] = 22] = "TokenState";
            SearchType[SearchType["AssetCalculationResult"] = 23] = "AssetCalculationResult";
            SearchType[SearchType["Equipment"] = 24] = "Equipment";
            SearchType[SearchType["CustomerAccount"] = 25] = "CustomerAccount";
            SearchType[SearchType["InspTemplate"] = 26] = "InspTemplate";
            SearchType[SearchType["ProblemLeaf"] = 27] = "ProblemLeaf";
            SearchType[SearchType["AssetSplitRecord"] = 28] = "AssetSplitRecord";
            SearchType[SearchType["PavementInsp"] = 29] = "PavementInsp";
            SearchType[SearchType["TvInspection"] = 30] = "TvInspection";
            SearchType[SearchType["Projects"] = 31] = "Projects";
        })(SearchType = Enums.SearchType || (Enums.SearchType = {}));
        var SearchView;
        (function (SearchView) {
            SearchView[SearchView["Grid"] = 0] = "Grid";
            SearchView[SearchView["Calendar"] = 1] = "Calendar";
            SearchView[SearchView["Map"] = 2] = "Map";
            SearchView[SearchView["Frequency"] = 3] = "Frequency";
            SearchView[SearchView["WorkOrderEntity"] = 4] = "WorkOrderEntity";
        })(SearchView = Enums.SearchView || (Enums.SearchView = {}));
        var SourceEventType;
        (function (SourceEventType) {
            SourceEventType[SourceEventType["WorkOrderManualEmail"] = 0] = "WorkOrderManualEmail";
            SourceEventType[SourceEventType["WorkOrderSubmitToChanged"] = 1] = "WorkOrderSubmitToChanged";
            SourceEventType[SourceEventType["WorkOrderCreated"] = 2] = "WorkOrderCreated";
            SourceEventType[SourceEventType["WorkOrderClosed"] = 3] = "WorkOrderClosed";
            SourceEventType[SourceEventType["WorkOrderPrintQueue"] = 4] = "WorkOrderPrintQueue";
            SourceEventType[SourceEventType["WorkOrderCanceled"] = 5] = "WorkOrderCanceled";
            SourceEventType[SourceEventType["WorkOrderDeleted"] = 6] = "WorkOrderDeleted";
            SourceEventType[SourceEventType["RequestManualCallerEmail"] = 7] = "RequestManualCallerEmail";
            SourceEventType[SourceEventType["RequestManualEmail"] = 8] = "RequestManualEmail";
            SourceEventType[SourceEventType["RequestSubmitToChanged"] = 9] = "RequestSubmitToChanged";
            SourceEventType[SourceEventType["RequestDispatchedToChanged"] = 10] = "RequestDispatchedToChanged";
            SourceEventType[SourceEventType["RequestCreated"] = 11] = "RequestCreated";
            SourceEventType[SourceEventType["RequestClosed"] = 12] = "RequestClosed";
            SourceEventType[SourceEventType["RequestCanceled"] = 13] = "RequestCanceled";
            SourceEventType[SourceEventType["RequestDeleted"] = 14] = "RequestDeleted";
            SourceEventType[SourceEventType["InspectionManualEmail"] = 15] = "InspectionManualEmail";
            SourceEventType[SourceEventType["InspectionCreated"] = 16] = "InspectionCreated";
            SourceEventType[SourceEventType["InspectionSubmitToChanged"] = 17] = "InspectionSubmitToChanged";
            SourceEventType[SourceEventType["InspectionClosed"] = 18] = "InspectionClosed";
            SourceEventType[SourceEventType["InspectionDeleted"] = 19] = "InspectionDeleted";
            SourceEventType[SourceEventType["InspectionCanceled"] = 20] = "InspectionCanceled";
            SourceEventType[SourceEventType["CommentMention"] = 21] = "CommentMention";
            SourceEventType[SourceEventType["RequestLaborAdded"] = 22] = "RequestLaborAdded";
            SourceEventType[SourceEventType["RequestLaborDeleted"] = 23] = "RequestLaborDeleted";
            SourceEventType[SourceEventType["WorkOrderLaborAdded"] = 24] = "WorkOrderLaborAdded";
            SourceEventType[SourceEventType["WorkOrderLaborDeleted"] = 25] = "WorkOrderLaborDeleted";
            SourceEventType[SourceEventType["CaObjectCreated"] = 26] = "CaObjectCreated";
            SourceEventType[SourceEventType["CaObjectUpdated"] = 27] = "CaObjectUpdated";
            SourceEventType[SourceEventType["CaObjectDeleted"] = 28] = "CaObjectDeleted";
            SourceEventType[SourceEventType["Unknown"] = 29] = "Unknown";
            SourceEventType[SourceEventType["WorkOrderStatusChanged"] = 30] = "WorkOrderStatusChanged";
            SourceEventType[SourceEventType["RequestStatusChanged"] = 31] = "RequestStatusChanged";
            SourceEventType[SourceEventType["InspectionStatusChanged"] = 32] = "InspectionStatusChanged";
            SourceEventType[SourceEventType["RequestCommentAdded"] = 33] = "RequestCommentAdded";
            SourceEventType[SourceEventType["RequestCommentUpdated"] = 34] = "RequestCommentUpdated";
            SourceEventType[SourceEventType["RequestCommentDeleted"] = 35] = "RequestCommentDeleted";
            SourceEventType[SourceEventType["WorkOrderCommentAdded"] = 36] = "WorkOrderCommentAdded";
            SourceEventType[SourceEventType["WorkOrderCommentUpdated"] = 37] = "WorkOrderCommentUpdated";
            SourceEventType[SourceEventType["WorkOrderCommentDeleted"] = 38] = "WorkOrderCommentDeleted";
            SourceEventType[SourceEventType["CaCorrectionCommentAdded"] = 39] = "CaCorrectionCommentAdded";
            SourceEventType[SourceEventType["CaCorrectionCommentUpdated"] = 40] = "CaCorrectionCommentUpdated";
            SourceEventType[SourceEventType["CaCorrectionCommentDeleted"] = 41] = "CaCorrectionCommentDeleted";
            SourceEventType[SourceEventType["CaTaskCommentAdded"] = 42] = "CaTaskCommentAdded";
            SourceEventType[SourceEventType["CaTaskCommentUpdated"] = 43] = "CaTaskCommentUpdated";
            SourceEventType[SourceEventType["CaTaskCommentDeleted"] = 44] = "CaTaskCommentDeleted";
            SourceEventType[SourceEventType["CaObjectCommentAdded"] = 45] = "CaObjectCommentAdded";
            SourceEventType[SourceEventType["CaObjectCommentUpdated"] = 46] = "CaObjectCommentUpdated";
            SourceEventType[SourceEventType["CaObjectCommentDeleted"] = 47] = "CaObjectCommentDeleted";
            SourceEventType[SourceEventType["CaTaskItemCompleted"] = 48] = "CaTaskItemCompleted";
            SourceEventType[SourceEventType["WoTaskAdded"] = 50] = "WoTaskAdded";
            SourceEventType[SourceEventType["WoTaskAssignedToChanged"] = 51] = "WoTaskAssignedToChanged";
            SourceEventType[SourceEventType["WoTaskCommentAdded"] = 52] = "WoTaskCommentAdded";
            SourceEventType[SourceEventType["WoTaskCommentDeleted"] = 53] = "WoTaskCommentDeleted";
            SourceEventType[SourceEventType["WoTaskCommentUpdated"] = 54] = "WoTaskCommentUpdated";
            SourceEventType[SourceEventType["WoTaskDeleted"] = 55] = "WoTaskDeleted";
            SourceEventType[SourceEventType["WoTaskProceedUpdated"] = 56] = "WoTaskProceedUpdated";
            SourceEventType[SourceEventType["WoTaskReworkUpdated"] = 57] = "WoTaskReworkUpdated";
            SourceEventType[SourceEventType["WoTaskStatusChanged"] = 58] = "WoTaskStatusChanged";
            SourceEventType[SourceEventType["WorkOrderReopened"] = 60] = "WorkOrderReopened";
            SourceEventType[SourceEventType["WorkOrderUncanceled"] = 61] = "WorkOrderUncanceled";
            SourceEventType[SourceEventType["RequestReopened"] = 62] = "RequestReopened";
            SourceEventType[SourceEventType["RequestUncanceled"] = 63] = "RequestUncanceled";
            SourceEventType[SourceEventType["InspectionReopened"] = 64] = "InspectionReopened";
            SourceEventType[SourceEventType["InspectionUncanceled"] = 65] = "InspectionUncanceled";
            SourceEventType[SourceEventType["CaTaskItemAdded"] = 66] = "CaTaskItemAdded";
            SourceEventType[SourceEventType["CaTaskItemDeleted"] = 67] = "CaTaskItemDeleted";
            SourceEventType[SourceEventType["CaTaskItemAvailable"] = 68] = "CaTaskItemAvailable";
            SourceEventType[SourceEventType["CaObjectAttachmentAdded"] = 69] = "CaObjectAttachmentAdded";
            SourceEventType[SourceEventType["CaObjectAttachmentDeleted"] = 70] = "CaObjectAttachmentDeleted";
            SourceEventType[SourceEventType["InspectionAttachmentAdded"] = 71] = "InspectionAttachmentAdded";
            SourceEventType[SourceEventType["InspectionAttachmentDeleted"] = 72] = "InspectionAttachmentDeleted";
            SourceEventType[SourceEventType["RequestAttachmentAdded"] = 73] = "RequestAttachmentAdded";
            SourceEventType[SourceEventType["RequestAttachmentDeleted"] = 74] = "RequestAttachmentDeleted";
            SourceEventType[SourceEventType["WorkOrderAttachmentAdded"] = 75] = "WorkOrderAttachmentAdded";
            SourceEventType[SourceEventType["WorkOrderAttachmentDeleted"] = 76] = "WorkOrderAttachmentDeleted";
            SourceEventType[SourceEventType["InspectionLaborAdded"] = 77] = "InspectionLaborAdded";
            SourceEventType[SourceEventType["InspectionLaborDeleted"] = 78] = "InspectionLaborDeleted";
            SourceEventType[SourceEventType["InspectionEquipmentAdded"] = 79] = "InspectionEquipmentAdded";
            SourceEventType[SourceEventType["InspectionEquipmentDeleted"] = 80] = "InspectionEquipmentDeleted";
            SourceEventType[SourceEventType["WorkOrderEquipmentAdded"] = 81] = "WorkOrderEquipmentAdded";
            SourceEventType[SourceEventType["WorkOrderEquipmentDeleted"] = 82] = "WorkOrderEquipmentDeleted";
            SourceEventType[SourceEventType["WorkOrderMaterialAdded"] = 83] = "WorkOrderMaterialAdded";
            SourceEventType[SourceEventType["WorkOrderMaterialDeleted"] = 84] = "WorkOrderMaterialDeleted";
            SourceEventType[SourceEventType["RequestCallerAdded"] = 85] = "RequestCallerAdded";
            SourceEventType[SourceEventType["RequestCallerDeleted"] = 86] = "RequestCallerDeleted";
            SourceEventType[SourceEventType["InspectionCommentAdded"] = 87] = "InspectionCommentAdded";
            SourceEventType[SourceEventType["InspectionCommentUpdated"] = 88] = "InspectionCommentUpdated";
            SourceEventType[SourceEventType["InspectionCommentDeleted"] = 89] = "InspectionCommentDeleted";
            SourceEventType[SourceEventType["CaAddressItemAdded"] = 90] = "CaAddressItemAdded";
            SourceEventType[SourceEventType["CaAddressItemDeleted"] = 91] = "CaAddressItemDeleted";
            SourceEventType[SourceEventType["CaFeesItemAdded"] = 92] = "CaFeesItemAdded";
            SourceEventType[SourceEventType["CaFeesItemWaiveFeeChanged"] = 93] = "CaFeesItemWaiveFeeChanged";
            SourceEventType[SourceEventType["CaFeesItemInvoicedChanged"] = 94] = "CaFeesItemInvoicedChanged";
            SourceEventType[SourceEventType["CaFeesItemDeleted"] = 95] = "CaFeesItemDeleted";
            SourceEventType[SourceEventType["ProjectAdded"] = 96] = "ProjectAdded";
            SourceEventType[SourceEventType["ProjectDeleted"] = 97] = "ProjectDeleted";
            SourceEventType[SourceEventType["ProjectStatusChanged"] = 98] = "ProjectStatusChanged";
            SourceEventType[SourceEventType["ProjectAssignedToChanged"] = 99] = "ProjectAssignedToChanged";
            SourceEventType[SourceEventType["ProjectApprovedByChanged"] = 100] = "ProjectApprovedByChanged";
            SourceEventType[SourceEventType["ProjectAttachmentAdded"] = 101] = "ProjectAttachmentAdded";
            SourceEventType[SourceEventType["ProjectAttachmentDeleted"] = 102] = "ProjectAttachmentDeleted";
            SourceEventType[SourceEventType["ProjectCommentAdded"] = 103] = "ProjectCommentAdded";
            SourceEventType[SourceEventType["ProjectCommentUpdated"] = 104] = "ProjectCommentUpdated";
            SourceEventType[SourceEventType["ProjectCommentDeleted"] = 105] = "ProjectCommentDeleted";
            SourceEventType[SourceEventType["WorkOrderProjectAdded"] = 106] = "WorkOrderProjectAdded";
            SourceEventType[SourceEventType["WorkOrderProjectRemoved"] = 107] = "WorkOrderProjectRemoved";
            SourceEventType[SourceEventType["RequestProjectAdded"] = 108] = "RequestProjectAdded";
            SourceEventType[SourceEventType["RequestProjectRemoved"] = 109] = "RequestProjectRemoved";
            SourceEventType[SourceEventType["InspectionProjectAdded"] = 110] = "InspectionProjectAdded";
            SourceEventType[SourceEventType["InspectionProjectRemoved"] = 111] = "InspectionProjectRemoved";
            SourceEventType[SourceEventType["CaObjectProjectAdded"] = 112] = "CaObjectProjectAdded";
            SourceEventType[SourceEventType["CaObjectProjectRemoved"] = 113] = "CaObjectProjectRemoved";
            SourceEventType[SourceEventType["ContractAttachmentAdded"] = 114] = "ContractAttachmentAdded";
            SourceEventType[SourceEventType["ContractAttachmentDeleted"] = 115] = "ContractAttachmentDeleted";
        })(SourceEventType = Enums.SourceEventType || (Enums.SourceEventType = {}));
        var StandardInspTableName;
        (function (StandardInspTableName) {
            StandardInspTableName[StandardInspTableName["SDYETEST"] = 0] = "SDYETEST";
            StandardInspTableName[StandardInspTableName["SMANHOLEINSP"] = 1] = "SMANHOLEINSP";
            StandardInspTableName[StandardInspTableName["SSMOKETEST"] = 2] = "SSMOKETEST";
            StandardInspTableName[StandardInspTableName["STVINSPECTION"] = 3] = "STVINSPECTION";
            StandardInspTableName[StandardInspTableName["WFIREHYDFLOWTEST"] = 4] = "WFIREHYDFLOWTEST";
            StandardInspTableName[StandardInspTableName["EQUIPCHANGEOUT"] = 5] = "EQUIPCHANGEOUT";
            StandardInspTableName[StandardInspTableName["WVALVDEVINSP"] = 6] = "WVALVDEVINSP";
            StandardInspTableName[StandardInspTableName["WHYDDEVINSP"] = 7] = "WHYDDEVINSP";
            StandardInspTableName[StandardInspTableName["SSTINLETINSP"] = 8] = "SSTINLETINSP";
        })(StandardInspTableName = Enums.StandardInspTableName || (Enums.StandardInspTableName = {}));
        var TemplateMapLayerSourceType;
        (function (TemplateMapLayerSourceType) {
            TemplateMapLayerSourceType[TemplateMapLayerSourceType["Invalid"] = 0] = "Invalid";
            TemplateMapLayerSourceType[TemplateMapLayerSourceType["Inspection"] = 1] = "Inspection";
            TemplateMapLayerSourceType[TemplateMapLayerSourceType["Case"] = 2] = "Case";
            TemplateMapLayerSourceType[TemplateMapLayerSourceType["Request"] = 3] = "Request";
            TemplateMapLayerSourceType[TemplateMapLayerSourceType["WorkOrder"] = 4] = "WorkOrder";
            TemplateMapLayerSourceType[TemplateMapLayerSourceType["InspectionTemplate"] = 5] = "InspectionTemplate";
            TemplateMapLayerSourceType[TemplateMapLayerSourceType["BusCaseTemplate"] = 6] = "BusCaseTemplate";
            TemplateMapLayerSourceType[TemplateMapLayerSourceType["RequestTemplate"] = 7] = "RequestTemplate";
            TemplateMapLayerSourceType[TemplateMapLayerSourceType["WorkOrderTemplate"] = 8] = "WorkOrderTemplate";
        })(TemplateMapLayerSourceType = Enums.TemplateMapLayerSourceType || (Enums.TemplateMapLayerSourceType = {}));
        var TimeIntervalUnit;
        (function (TimeIntervalUnit) {
            TimeIntervalUnit[TimeIntervalUnit["HOUR"] = 0] = "HOUR";
            TimeIntervalUnit[TimeIntervalUnit["DAY"] = 1] = "DAY";
            TimeIntervalUnit[TimeIntervalUnit["WEEK"] = 2] = "WEEK";
            TimeIntervalUnit[TimeIntervalUnit["MONTH"] = 3] = "MONTH";
        })(TimeIntervalUnit = Enums.TimeIntervalUnit || (Enums.TimeIntervalUnit = {}));
        var TransactionType;
        (function (TransactionType) {
            TransactionType[TransactionType["NULL"] = 0] = "NULL";
            TransactionType[TransactionType["AUDIT"] = 1] = "AUDIT";
            TransactionType[TransactionType["ISSUE"] = 2] = "ISSUE";
            TransactionType[TransactionType["RECEIVE"] = 3] = "RECEIVE";
            TransactionType[TransactionType["TRANSFER"] = 4] = "TRANSFER";
            TransactionType[TransactionType["FRTRASH"] = 5] = "FRTRASH";
            TransactionType[TransactionType["TOTRASH"] = 6] = "TOTRASH";
        })(TransactionType = Enums.TransactionType || (Enums.TransactionType = {}));
        var TraverseNetworkDirection;
        (function (TraverseNetworkDirection) {
            TraverseNetworkDirection[TraverseNetworkDirection["Unknown"] = 0] = "Unknown";
            TraverseNetworkDirection[TraverseNetworkDirection["Up"] = 1] = "Up";
            TraverseNetworkDirection[TraverseNetworkDirection["Down"] = 2] = "Down";
            TraverseNetworkDirection[TraverseNetworkDirection["Both"] = 3] = "Both";
        })(TraverseNetworkDirection = Enums.TraverseNetworkDirection || (Enums.TraverseNetworkDirection = {}));
        var TreeNodeTextType;
        (function (TreeNodeTextType) {
            TreeNodeTextType[TreeNodeTextType["C"] = 0] = "C";
            TreeNodeTextType[TreeNodeTextType["CD"] = 1] = "CD";
            TreeNodeTextType[TreeNodeTextType["D"] = 2] = "D";
        })(TreeNodeTextType = Enums.TreeNodeTextType || (Enums.TreeNodeTextType = {}));
        var TreeNodeType;
        (function (TreeNodeType) {
            TreeNodeType[TreeNodeType["R"] = 0] = "R";
            TreeNodeType[TreeNodeType["N"] = 1] = "N";
            TreeNodeType[TreeNodeType["L"] = 2] = "L";
            TreeNodeType[TreeNodeType["Null"] = 3] = "Null";
        })(TreeNodeType = Enums.TreeNodeType || (Enums.TreeNodeType = {}));
        var TvObservationCause;
        (function (TvObservationCause) {
            TvObservationCause[TvObservationCause["S"] = 0] = "S";
            TvObservationCause[TvObservationCause["I"] = 1] = "I";
            TvObservationCause[TvObservationCause["R"] = 2] = "R";
            TvObservationCause[TvObservationCause["O"] = 3] = "O";
        })(TvObservationCause = Enums.TvObservationCause || (Enums.TvObservationCause = {}));
        var TvObservationMethod;
        (function (TvObservationMethod) {
            TvObservationMethod[TvObservationMethod["STANDARD"] = 0] = "STANDARD";
            TvObservationMethod[TvObservationMethod["CCTV"] = 1] = "CCTV";
        })(TvObservationMethod = Enums.TvObservationMethod || (Enums.TvObservationMethod = {}));
        var UniversalCustomFieldTable;
        (function (UniversalCustomFieldTable) {
            UniversalCustomFieldTable[UniversalCustomFieldTable["CONTRACT"] = 0] = "CONTRACT";
            UniversalCustomFieldTable[UniversalCustomFieldTable["CUSTOMERCALL"] = 1] = "CUSTOMERCALL";
            UniversalCustomFieldTable[UniversalCustomFieldTable["INSPECTION"] = 2] = "INSPECTION";
            UniversalCustomFieldTable[UniversalCustomFieldTable["REQUEST"] = 3] = "REQUEST";
            UniversalCustomFieldTable[UniversalCustomFieldTable["WORKORDER"] = 4] = "WORKORDER";
            UniversalCustomFieldTable[UniversalCustomFieldTable["PROJECT"] = 5] = "PROJECT";
            UniversalCustomFieldTable[UniversalCustomFieldTable["STVINSPECTION"] = 6] = "STVINSPECTION";
        })(UniversalCustomFieldTable = Enums.UniversalCustomFieldTable || (Enums.UniversalCustomFieldTable = {}));
        var VerificationStatus;
        (function (VerificationStatus) {
            VerificationStatus[VerificationStatus["Unverified"] = 0] = "Unverified";
            VerificationStatus[VerificationStatus["Pass"] = 1] = "Pass";
            VerificationStatus[VerificationStatus["Fail"] = 2] = "Fail";
        })(VerificationStatus = Enums.VerificationStatus || (Enums.VerificationStatus = {}));
        var WebHookCustomPacketTemplateFlag;
        (function (WebHookCustomPacketTemplateFlag) {
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["Unknown"] = 0] = "Unknown";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["ApiUserToken"] = 1] = "ApiUserToken";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["Comments"] = 2] = "Comments";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["CwWkid"] = 3] = "CwWkid";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["GetDate"] = 4] = "GetDate";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["QuestionAnswer"] = 5] = "QuestionAnswer";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["ServiceResourceSecurityToken"] = 6] = "ServiceResourceSecurityToken";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["GisItemOid"] = 7] = "GisItemOid";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["GisItemGlobalId"] = 8] = "GisItemGlobalId";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["CancelledByPager"] = 9] = "CancelledByPager";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["CancelledByWorkPhone"] = 10] = "CancelledByWorkPhone";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["ClosedByPager"] = 11] = "ClosedByPager";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["ClosedByWorkPhone"] = 12] = "ClosedByWorkPhone";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["CurrentUserPager"] = 13] = "CurrentUserPager";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["CurrentUserWorkPhone"] = 14] = "CurrentUserWorkPhone";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["DispatchOpenByPager"] = 15] = "DispatchOpenByPager";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["DispatchOpenByWorkPhone"] = 16] = "DispatchOpenByWorkPhone";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["DispatchToPager"] = 17] = "DispatchToPager";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["DispatchToWorkPhone"] = 18] = "DispatchToWorkPhone";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["InitiatedByPager"] = 19] = "InitiatedByPager";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["InitiatedByWorkPhone"] = 20] = "InitiatedByWorkPhone";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["InspectedByPager"] = 21] = "InspectedByPager";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["InspectedByWorkPhone"] = 22] = "InspectedByWorkPhone";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["RequestedByPager"] = 23] = "RequestedByPager";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["RequestedByWorkPhone"] = 24] = "RequestedByWorkPhone";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["SubmitToOpenByPager"] = 25] = "SubmitToOpenByPager";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["SubmitToOpenByWorkPhone"] = 26] = "SubmitToOpenByWorkPhone";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["SubmitToPager"] = 27] = "SubmitToPager";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["SubmitToWorkPhone"] = 28] = "SubmitToWorkPhone";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["SupervisorPager"] = 29] = "SupervisorPager";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["SupervisorWorkPhone"] = 30] = "SupervisorWorkPhone";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["WorkCompletedByPager"] = 31] = "WorkCompletedByPager";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["WorkCompletedByWorkPhone"] = 32] = "WorkCompletedByWorkPhone";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["CancelledByPager_Numeric"] = 33] = "CancelledByPager_Numeric";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["CancelledByWorkPhone_Numeric"] = 34] = "CancelledByWorkPhone_Numeric";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["ClosedByPager_Numeric"] = 35] = "ClosedByPager_Numeric";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["ClosedByWorkPhone_Numeric"] = 36] = "ClosedByWorkPhone_Numeric";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["CurrentUserPager_Numeric"] = 37] = "CurrentUserPager_Numeric";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["CurrentUserWorkPhone_Numeric"] = 38] = "CurrentUserWorkPhone_Numeric";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["DispatchOpenByPager_Numeric"] = 39] = "DispatchOpenByPager_Numeric";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["DispatchOpenByWorkPhone_Numeric"] = 40] = "DispatchOpenByWorkPhone_Numeric";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["DispatchToPager_Numeric"] = 41] = "DispatchToPager_Numeric";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["DispatchToWorkPhone_Numeric"] = 42] = "DispatchToWorkPhone_Numeric";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["InitiatedByPager_Numeric"] = 43] = "InitiatedByPager_Numeric";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["InitiatedByWorkPhone_Numeric"] = 44] = "InitiatedByWorkPhone_Numeric";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["InspectedByPager_Numeric"] = 45] = "InspectedByPager_Numeric";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["InspectedByWorkPhone_Numeric"] = 46] = "InspectedByWorkPhone_Numeric";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["RequestedByPager_Numeric"] = 47] = "RequestedByPager_Numeric";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["RequestedByWorkPhone_Numeric"] = 48] = "RequestedByWorkPhone_Numeric";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["SubmitToOpenByPager_Numeric"] = 49] = "SubmitToOpenByPager_Numeric";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["SubmitToOpenByWorkPhone_Numeric"] = 50] = "SubmitToOpenByWorkPhone_Numeric";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["SubmitToPager_Numeric"] = 51] = "SubmitToPager_Numeric";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["SubmitToWorkPhone_Numeric"] = 52] = "SubmitToWorkPhone_Numeric";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["SupervisorPager_Numeric"] = 53] = "SupervisorPager_Numeric";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["SupervisorWorkPhone_Numeric"] = 54] = "SupervisorWorkPhone_Numeric";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["WorkCompletedByPager_Numeric"] = 55] = "WorkCompletedByPager_Numeric";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["WorkCompletedByWorkPhone_Numeric"] = 56] = "WorkCompletedByWorkPhone_Numeric";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["BaseObjectAsJson"] = 57] = "BaseObjectAsJson";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["RequestWorkOrderIds"] = 58] = "RequestWorkOrderIds";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["WorkOrderRequestIds"] = 59] = "WorkOrderRequestIds";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["GetDay"] = 60] = "GetDay";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["GetDayOfWeek"] = 61] = "GetDayOfWeek";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["GetDayOfWeek_Numeric"] = 62] = "GetDayOfWeek_Numeric";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["GetDayOfYear"] = 63] = "GetDayOfYear";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["GetHour"] = 64] = "GetHour";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["GetMinute"] = 65] = "GetMinute";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["GetMonth_Numeric"] = 66] = "GetMonth_Numeric";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["GetSecond"] = 67] = "GetSecond";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["GetUtcDateTimeString"] = 68] = "GetUtcDateTimeString";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["CurrentUserSid"] = 69] = "CurrentUserSid";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["CurrentUserUniqueName"] = 70] = "CurrentUserUniqueName";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["SiteBaseUrl"] = 71] = "SiteBaseUrl";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["UserIdToEmployeeSid"] = 72] = "UserIdToEmployeeSid";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["CaseInspectionIds"] = 73] = "CaseInspectionIds";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["CaseRequestIds"] = 74] = "CaseRequestIds";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["CaseWorkOrderIds"] = 75] = "CaseWorkOrderIds";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["CaseWorkOrderSids"] = 76] = "CaseWorkOrderSids";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["InspectionCaObjectIds"] = 77] = "InspectionCaObjectIds";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["InspectionRequestIds"] = 78] = "InspectionRequestIds";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["InspectionWorkOrderIds"] = 79] = "InspectionWorkOrderIds";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["InspectionWorkOrderSids"] = 80] = "InspectionWorkOrderSids";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["RequestCaObjectIds"] = 81] = "RequestCaObjectIds";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["RequestInspectionIds"] = 82] = "RequestInspectionIds";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["RequestWorkOrderSids"] = 83] = "RequestWorkOrderSids";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["WorkOrderCaObjectIds"] = 84] = "WorkOrderCaObjectIds";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["WorkOrderInspectionIds"] = 85] = "WorkOrderInspectionIds";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["CategoryCustomFieldName"] = 86] = "CategoryCustomFieldName";
            WebHookCustomPacketTemplateFlag[WebHookCustomPacketTemplateFlag["CategoryCustomFieldValue"] = 87] = "CategoryCustomFieldValue";
        })(WebHookCustomPacketTemplateFlag = Enums.WebHookCustomPacketTemplateFlag || (Enums.WebHookCustomPacketTemplateFlag = {}));
        var WebHookOutputType;
        (function (WebHookOutputType) {
            WebHookOutputType[WebHookOutputType["JSON"] = 0] = "JSON";
            WebHookOutputType[WebHookOutputType["CSV"] = 1] = "CSV";
        })(WebHookOutputType = Enums.WebHookOutputType || (Enums.WebHookOutputType = {}));
        var WebHookPacketModel;
        (function (WebHookPacketModel) {
            WebHookPacketModel[WebHookPacketModel["Simple"] = 0] = "Simple";
            WebHookPacketModel[WebHookPacketModel["Custom"] = 1] = "Custom";
        })(WebHookPacketModel = Enums.WebHookPacketModel || (Enums.WebHookPacketModel = {}));
        var WidgetContainerTabType;
        (function (WidgetContainerTabType) {
            WidgetContainerTabType[WidgetContainerTabType["Domain"] = 0] = "Domain";
            WidgetContainerTabType[WidgetContainerTabType["User"] = 1] = "User";
        })(WidgetContainerTabType = Enums.WidgetContainerTabType || (Enums.WidgetContainerTabType = {}));
        var WidgetContainerType;
        (function (WidgetContainerType) {
            WidgetContainerType[WidgetContainerType["Domain"] = 0] = "Domain";
            WidgetContainerType[WidgetContainerType["User"] = 1] = "User";
        })(WidgetContainerType = Enums.WidgetContainerType || (Enums.WidgetContainerType = {}));
        var WOEvent;
        (function (WOEvent) {
            WOEvent[WOEvent["CLOSE"] = 1] = "CLOSE";
            WOEvent[WOEvent["INITIATE"] = 2] = "INITIATE";
            WOEvent[WOEvent["ADDENTITY"] = 3] = "ADDENTITY";
        })(WOEvent = Enums.WOEvent || (Enums.WOEvent = {}));
        var WOExpenseType;
        (function (WOExpenseType) {
            WOExpenseType[WOExpenseType["MAINT"] = 0] = "MAINT";
            WOExpenseType[WOExpenseType["CIP"] = 1] = "CIP";
        })(WOExpenseType = Enums.WOExpenseType || (Enums.WOExpenseType = {}));
        var WOOutputType;
        (function (WOOutputType) {
            WOOutputType[WOOutputType["WorkOrder"] = 0] = "WorkOrder";
            WOOutputType[WOOutputType["Map"] = 1] = "Map";
            WOOutputType[WOOutputType["WorkOrderAndMap"] = 2] = "WorkOrderAndMap";
        })(WOOutputType = Enums.WOOutputType || (Enums.WOOutputType = {}));
        var WorkDurationUnit;
        (function (WorkDurationUnit) {
            WorkDurationUnit[WorkDurationUnit["Null"] = 0] = "Null";
            WorkDurationUnit[WorkDurationUnit["H"] = 1] = "H";
            WorkDurationUnit[WorkDurationUnit["D"] = 2] = "D";
        })(WorkDurationUnit = Enums.WorkDurationUnit || (Enums.WorkDurationUnit = {}));
        var WorkType;
        (function (WorkType) {
            WorkType[WorkType["ALL"] = 0] = "ALL";
            WorkType[WorkType["WORKORDER"] = 1] = "WORKORDER";
            WorkType[WorkType["INSPECTION"] = 2] = "INSPECTION";
            WorkType[WorkType["REQUEST"] = 3] = "REQUEST";
        })(WorkType = Enums.WorkType || (Enums.WorkType = {}));
        var WOStage;
        (function (WOStage) {
            WOStage[WOStage["PROPOSED"] = 0] = "PROPOSED";
            WOStage[WOStage["ACTUAL"] = 1] = "ACTUAL";
        })(WOStage = Enums.WOStage || (Enums.WOStage = {}));
        var WritePdf;
        (function (WritePdf) {
            WritePdf[WritePdf["Fees"] = 0] = "Fees";
            WritePdf[WritePdf["Escrow"] = 1] = "Escrow";
            WritePdf[WritePdf["Deposit"] = 2] = "Deposit";
            WritePdf[WritePdf["EscrowPayment"] = 3] = "EscrowPayment";
        })(WritePdf = Enums.WritePdf || (Enums.WritePdf = {}));
    })(Enums = exports.Enums || (exports.Enums = {}));
});
