import { PromiseTypes } from '../../../core/promise';
import { IApiService } from '../../../http/api-service';
import { SearchServiceTypes as SvcDef } from '../../interfaces/Ams/SearchService';
import AbortablePromise = PromiseTypes.AbortablePromise;
import Requests = SvcDef.Requests;
import Responses = SvcDef.Responses;
import ISearchService = SvcDef.ISearchService;
export * from '../../../http/api-service';
export * from '../../interfaces/Ams/SearchService';
export declare class SearchService implements ISearchService {
    private _service;
    constructor(service: IApiService);
    AssetCalculationResultSaved(request: Requests.AssetCalculationResultSaved): AbortablePromise<Responses.Saved>;
    Definition(request: Requests.Definition): AbortablePromise<Responses.Definition>;
    DefinitionNames(request: Requests.DefinitionNames): AbortablePromise<Responses.Saved>;
    Definitions(request: Requests.Definitions): AbortablePromise<Responses.Definitions>;
    DeleteDefinitions(request: Requests.DeleteDefinitions): AbortablePromise<Responses.DeleteDefinitions>;
    DisplayFields(request: Requests.DisplayFields): AbortablePromise<Responses.DisplayFields>;
    Execute(request: Requests.Execute): AbortablePromise<Responses.Execute>;
    GISSaved(request: Requests.GISSaved): AbortablePromise<Responses.Saved>;
    InspectionSaved(request: Requests.InspectionSaved): AbortablePromise<Responses.Saved>;
    MaterialSaved(request: Requests.MaterialSaved): AbortablePromise<Responses.Saved>;
    PllSaved(request: Requests.PllSaved): AbortablePromise<Responses.Saved>;
    RecentActivity(request: Requests.RecentActivity): AbortablePromise<Responses.RecentActivity>;
    RequestSaved(request: Requests.RequestSaved): AbortablePromise<Responses.Saved>;
    RequisitionSaved(request: Requests.RequisitionSaved): AbortablePromise<Responses.Saved>;
    SavedByType(request: Requests.SavedByType): AbortablePromise<Responses.Saved>;
    SaveDefinition(request: Requests.SaveDefinition): AbortablePromise<Responses.SaveDefinition>;
    StoreTransactionSaved(request: Requests.StoreTransactionSaved): AbortablePromise<Responses.Saved>;
    Types(request: Requests.Types): AbortablePromise<Responses.Types>;
    UpdateEurl(request: Requests.UpdateEurl): AbortablePromise<Responses.UpdateEurl>;
    WorkActivitySaved(request: Requests.WorkActivitySaved): AbortablePromise<Responses.Saved>;
    WorkOrderEntitySaved(request: Requests.WorkOrderEntitySaved): AbortablePromise<Responses.Saved>;
    WorkOrderSaved(request: Requests.WorkOrderSaved): AbortablePromise<Responses.Saved>;
}
